PROMPT ============================================================
PROMPT v4.2.0 Graph Engineering - version-scoped Edge identity
PROMPT ============================================================

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_EDGES DROP CONSTRAINT PK_GRAPH_EDGES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_EDGES ADD CONSTRAINT PK_GRAPH_EDGES PRIMARY KEY (GRAPH_VERSION_ID, EDGE_ID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2261, -955) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROPERTY GRAPH ORACLE_EXECUTION_GRAPH';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -42421 THEN
            RAISE;
        END IF;
END;
/

CREATE PROPERTY GRAPH ORACLE_EXECUTION_GRAPH
  VERTEX TABLES (
    GRAPH_DEFINITIONS
      KEY (GRAPH_ID)
      PROPERTIES (GRAPH_ID, GRAPH_NAME, OWNER_REF, STATUS),
    GRAPH_VERSIONS
      KEY (GRAPH_VERSION_ID)
      PROPERTIES (GRAPH_VERSION_ID, GRAPH_ID, VERSION_NO, STATUS, DEFINITION_DIGEST),
    GRAPH_NODES
      KEY (GRAPH_VERSION_ID, NODE_KEY)
      PROPERTIES (NODE_ID, GRAPH_VERSION_ID, NODE_KEY, NODE_TYPE, TYPE_VERSION, SIDE_EFFECT_CLASS)
  )
  EDGE TABLES (
    GRAPH_EDGES
      KEY (GRAPH_VERSION_ID, EDGE_ID)
      SOURCE KEY (GRAPH_VERSION_ID, SOURCE_NODE_KEY)
        REFERENCES GRAPH_NODES (GRAPH_VERSION_ID, NODE_KEY)
      DESTINATION KEY (GRAPH_VERSION_ID, TARGET_NODE_KEY)
        REFERENCES GRAPH_NODES (GRAPH_VERSION_ID, NODE_KEY)
      PROPERTIES (EDGE_ID, GRAPH_VERSION_ID, EDGE_KIND, DECISION_TYPE, ORDER_INDEX)
  );

PROMPT v4.2.0 version-scoped Edge identity is ready.
