PROMPT ============================================================
PROMPT AI Agent Infra v3.10.1 - Community Edition - Schema Deployment
PROMPT ============================================================

WHENEVER SQLERROR CONTINUE

PROMPT Checking for existing deployment...
DECLARE
    v_count NUMBER;
    v_version VARCHAR2(32);
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SYSTEM_CONFIG';
    IF v_count > 0 THEN
        SELECT CONFIG_VALUE INTO v_version 
        FROM SYSTEM_CONFIG 
        WHERE CONFIG_KEY = 'schema_version';
        DBMS_OUTPUT.PUT_LINE('================================================');
        DBMS_OUTPUT.PUT_LINE('EXISTING DEPLOYMENT DETECTED: schema_version = ' || v_version);
        DBMS_OUTPUT.PUT_LINE('================================================');
        DBMS_OUTPUT.PUT_LINE('This database already has AI Agent Infra deployed.');
        DBMS_OUTPUT.PUT_LINE('To upgrade, use upgrade scripts instead of full deployment.');
        DBMS_OUTPUT.PUT_LINE('To reinitialize (DESTRUCTIVE), manually drop all tables first:');
        DBMS_OUTPUT.PUT_LINE('  BEGIN');
        DBMS_OUTPUT.PUT_LINE('    FOR r IN (SELECT table_name FROM user_tables WHERE table_name != ''DBTOOLS$MCP_LOG'') LOOP');
        DBMS_OUTPUT.PUT_LINE('      EXECUTE IMMEDIATE ''DROP TABLE "'' || r.table_name || ''" CASCADE CONSTRAINTS PURGE'';');
        DBMS_OUTPUT.PUT_LINE('    END LOOP;');
        DBMS_OUTPUT.PUT_LINE('  END;');
        DBMS_OUTPUT.PUT_LINE('  /');
        DBMS_OUTPUT.PUT_LINE('================================================');
        RAISE_APPLICATION_ERROR(-20001, 'Deployment aborted: existing deployment found. Schema version: ' || v_version);
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
    WHEN OTHERS THEN
        IF SQLCODE = -20001 THEN
            RAISE;
        END IF;
        NULL;
END;
/

CREATE OR REPLACE PROCEDURE safe_ddl(p_sql IN VARCHAR2) IS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SAFE_DDL skipped: ' || p_sql || ' - ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE safe_idx(p_sql IN VARCHAR2) IS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            DBMS_OUTPUT.PUT_LINE('SAFE_IDX error: ' || p_sql || ' - ' || SQLERRM);
        END IF;
END;
/

PROMPT Dropping old property graph...
EXEC safe_ddl('DROP PROPERTY GRAPH IF EXISTS ORACLE_MEMORY_GRAPH');

PROMPT Dropping old duality views...
EXEC safe_ddl('DROP VIEW IF EXISTS MEMORY_DV');
EXEC safe_ddl('DROP VIEW IF EXISTS KNOWLEDGE_DV');
EXEC safe_ddl('DROP VIEW IF EXISTS WORKSPACE_DV');
EXEC safe_ddl('DROP VIEW IF EXISTS CONTEXT_DV');
EXEC safe_ddl('DROP VIEW IF EXISTS SPEC_DV');
EXEC safe_ddl('DROP VIEW IF EXISTS COLLAB_GROUP_DV');

PROMPT Dropping all tables...
BEGIN
    FOR r IN (SELECT table_name FROM user_tables WHERE table_name != 'DBTOOLS$MCP_LOG') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE "' || r.table_name || '" CASCADE CONSTRAINTS PURGE';
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Skip: ' || r.table_name || ' - ' || SQLERRM);
        END;
    END LOOP;
    FOR r IN (SELECT table_name FROM user_tables WHERE table_name != 'DBTOOLS$MCP_LOG') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE "' || r.table_name || '" CASCADE CONSTRAINTS PURGE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

PROMPT ============================================================
PROMPT 1. ENTITIES (Partitioned by LIST + RANGE)
PROMPT ============================================================

CREATE TABLE ENTITIES (
    ENTITY_ID       VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE     VARCHAR2(32)  NOT NULL,
    TITLE           VARCHAR2(512) NOT NULL,
    CONTENT         CLOB,
    SUMMARY         VARCHAR2(2000),
    CATEGORY        VARCHAR2(64),
    STATUS          VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    OWNED_BY_AGENT  VARCHAR2(64),
    SOURCE_AGENT    VARCHAR2(64),
    VISIBILITY      VARCHAR2(16)  DEFAULT 'PRIVATE' NOT NULL,
    IMPORTANCE      NUMBER(3,0)   DEFAULT 5 NOT NULL,
    RETRIEVAL_COUNT NUMBER(10,0)  DEFAULT 0 NOT NULL,
    WORKSPACE_ID    VARCHAR2(64),
    EXPIRES_AT      TIMESTAMP,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITIES PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_ENTITIES_STATUS CHECK (STATUS IN ('ACTIVE','ARCHIVED','DELETED','DRAFT')),
    CONSTRAINT CK_ENTITIES_VISIBILITY CHECK (VISIBILITY IN ('PRIVATE','SHARED','PUBLIC')),
    CONSTRAINT CK_ENTITIES_IMPORTANCE CHECK (IMPORTANCE BETWEEN 1 AND 10),
    CONSTRAINT CK_ENTITIES_TYPE CHECK (ENTITY_TYPE IN ('MEMORY','KNOWLEDGE','TASK_OUTPUT','EXPERIENCE','HARNESS_TEMPLATE','SPEC','SKILL','LOOP_DEFINITION','AGENT','TASK_STEP','APPROVAL','LOOP_ITERATION','OTHER'))
) PARTITION BY LIST (ENTITY_TYPE)
SUBPARTITION BY RANGE (CREATED_AT)
SUBPARTITION TEMPLATE (
    SUBPARTITION SP_2026Q1 VALUES LESS THAN (TO_DATE('2026-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q2 VALUES LESS THAN (TO_DATE('2026-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q3 VALUES LESS THAN (TO_DATE('2026-10-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q4 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q1 VALUES LESS THAN (TO_DATE('2027-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q2 VALUES LESS THAN (TO_DATE('2027-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_FUTURE VALUES LESS THAN (MAXVALUE)
)
(
    PARTITION P_MEMORY        VALUES ('MEMORY'),
    PARTITION P_KNOWLEDGE     VALUES ('KNOWLEDGE'),
    PARTITION P_TASK_OUTPUT   VALUES ('TASK_OUTPUT'),
    PARTITION P_EXPERIENCE    VALUES ('EXPERIENCE'),
    PARTITION P_HARNESS       VALUES ('HARNESS_TEMPLATE'),
    PARTITION P_SPEC         VALUES ('SPEC'),
    PARTITION P_SKILL        VALUES ('SKILL'),
    PARTITION P_OTHERS        VALUES (DEFAULT)
);

ALTER TABLE ENTITIES ADD CONSTRAINT UK_ENTITIES_ID UNIQUE (ENTITY_ID);

PROMPT ============================================================
PROMPT 2. ENTITY_EDGES (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE ENTITY_EDGES (
    EDGE_ID       VARCHAR2(64)  NOT NULL,
    SOURCE_ID     VARCHAR2(64)  NOT NULL,
    SOURCE_TYPE   VARCHAR2(32)  NOT NULL,
    TARGET_ID     VARCHAR2(64)  NOT NULL,
    EDGE_TYPE     VARCHAR2(64)  NOT NULL,
    STRENGTH      NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    CONFIDENCE    NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    METADATA      JSON,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITY_EDGES PRIMARY KEY (EDGE_ID, SOURCE_ID),
    CONSTRAINT FK_EDGE_SOURCE FOREIGN KEY (SOURCE_ID, SOURCE_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE) ON DELETE CASCADE,
    CONSTRAINT CK_EDGE_STRENGTH CHECK (STRENGTH BETWEEN 0 AND 1),
    CONSTRAINT CK_EDGE_CONFIDENCE CHECK (CONFIDENCE BETWEEN 0 AND 1)
) PARTITION BY REFERENCE (FK_EDGE_SOURCE);

ALTER TABLE ENTITY_EDGES ADD CONSTRAINT UK_EDGES_ID UNIQUE (EDGE_ID);

PROMPT ============================================================
PROMPT 3. KNOWLEDGE_META (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE KNOWLEDGE_META (
    ENTITY_ID       VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE     VARCHAR2(32)  DEFAULT 'KNOWLEDGE' NOT NULL,
    DOMAIN          VARCHAR2(128),
    TOPIC           VARCHAR2(256),
    DIFFICULTY      VARCHAR2(16)  DEFAULT 'INTERMEDIATE' NOT NULL,
    REVIEW_COUNT    NUMBER(10,0)  DEFAULT 0 NOT NULL,
    LAST_REVIEWED   TIMESTAMP,
    NEXT_REVIEW     TIMESTAMP,
    CONSTRAINT PK_KNOWLEDGE_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_KM_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE) ON DELETE CASCADE,
    CONSTRAINT CK_KM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'KNOWLEDGE'),
    CONSTRAINT CK_KM_DIFFICULTY CHECK (DIFFICULTY IN ('BEGINNER','INTERMEDIATE','ADVANCED','EXPERT'))
) PARTITION BY REFERENCE (FK_KM_ENTITY);

PROMPT ============================================================
PROMPT 4. ENTITY_EMBEDDINGS (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE ENTITY_EMBEDDINGS (
    ENTITY_ID       VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE     VARCHAR2(32)  NOT NULL,
    EMBEDDING       VECTOR NOT NULL,
    EMBEDDING_MODEL VARCHAR2(128),
    EMBEDDING_DIM   NUMBER(5,0)   NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITY_EMBEDDINGS PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_EE_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE) ON DELETE CASCADE
) PARTITION BY REFERENCE (FK_EE_ENTITY);

PROMPT ============================================================
PROMPT 5. HARNESS_META (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE HARNESS_META (
    ENTITY_ID         VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE       VARCHAR2(32)  DEFAULT 'HARNESS_TEMPLATE' NOT NULL,
    TEMPLATE_VERSION  VARCHAR2(32)  NOT NULL,
    INPUT_SCHEMA      JSON,
    OUTPUT_SCHEMA     JSON,
    EXECUTION_MODE    VARCHAR2(32)  DEFAULT 'SEQUENTIAL' NOT NULL,
    CONSTRAINT PK_HARNESS_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_HM_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE) ON DELETE CASCADE,
    CONSTRAINT CK_HM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'HARNESS_TEMPLATE'),
    CONSTRAINT CK_HM_EXEC_MODE CHECK (EXECUTION_MODE IN ('SEQUENTIAL','PARALLEL','CONDITIONAL'))
) PARTITION BY REFERENCE (FK_HM_ENTITY);


PROMPT ============================================================
PROMPT 11b. CONTEXT_BRANCHES (Non-Partitioned) [NEW v3.3.0]
PROMPT ============================================================

CREATE TABLE CONTEXT_BRANCHES (
    BRANCH_ID        VARCHAR2(64)  PRIMARY KEY,
    WORKSPACE_ID     VARCHAR2(64)  NOT NULL,
    PARENT_BRANCH_ID VARCHAR2(64),
    FORK_CONTEXT_ID  VARCHAR2(64),
    FORK_SESSION_ID  VARCHAR2(64),
    BRANCH_NAME      VARCHAR2(256) NOT NULL,
    BRANCH_TYPE      VARCHAR2(32)  NOT NULL,
    BRANCH_STATUS    VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    AGENT_ID         VARCHAR2(64),
    SOURCE_AGENT_ID  VARCHAR2(64),
    BRANCH_PURPOSE   VARCHAR2(1000),
    METADATA         JSON,
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CLOSED_AT        TIMESTAMP,
    CONSTRAINT FK_CB_PARENT FOREIGN KEY (PARENT_BRANCH_ID) REFERENCES CONTEXT_BRANCHES(BRANCH_ID) ON DELETE SET NULL,
    CONSTRAINT CK_CB_TYPE CHECK (BRANCH_TYPE IN ('EXPLORATION','ROLLBACK','HANDOFF','PARALLEL')),
    CONSTRAINT CK_CB_STATUS CHECK (BRANCH_STATUS IN ('ACTIVE','MERGED','ABANDONED','PAUSED'))
);

PROMPT ============================================================

PROMPT 5b. SPEC_META (Reference Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE SPEC_META (
    ENTITY_ID           VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE         VARCHAR2(32)  DEFAULT 'SPEC' NOT NULL,
    SPEC_VERSION        NUMBER(6,0)   DEFAULT 1 NOT NULL,
    SPEC_STATUS         VARCHAR2(32)  DEFAULT 'DRAFT' NOT NULL,
    ACCEPTANCE_CRITERIA JSON,
    "CONSTRAINTS"         JSON,
    SPEC_SCOPE          VARCHAR2(64),
    COMPLEXITY          VARCHAR2(16)  DEFAULT 'MEDIUM' NOT NULL,
    BRANCH_ID           VARCHAR2(64),
    PARENT_SPEC_ID      VARCHAR2(64),
    CONSTRAINT PK_SPEC_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_SM_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE) ON DELETE CASCADE,
    CONSTRAINT CK_SM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'SPEC'),
    CONSTRAINT CK_SM_SPEC_STATUS CHECK (SPEC_STATUS IN ('DRAFT','REVIEWED','APPROVED','IMPLEMENTED','DEPRECATED')),
    CONSTRAINT CK_SM_COMPLEXITY CHECK (COMPLEXITY IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT FK_SM_PARENT FOREIGN KEY (PARENT_SPEC_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT FK_SM_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES CONTEXT_BRANCHES(BRANCH_ID) ON DELETE SET NULL
) PARTITION BY REFERENCE (FK_SM_ENTITY);

PROMPT ============================================================
PROMPT 5c. SKILL_META (Reference Partitioned) [NEW v3.1.0]
PROMPT ============================================================

CREATE TABLE SKILL_META (
    ENTITY_ID           VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE         VARCHAR2(32)  DEFAULT 'SKILL' NOT NULL,
    SKILL_NAME          VARCHAR2(256) NOT NULL,
    SKILL_VERSION       VARCHAR2(32)  DEFAULT '1.0.0' NOT NULL,
    SKILL_TYPE          VARCHAR2(32)  DEFAULT 'CUSTOM' NOT NULL,
    SKILL_FORMAT        VARCHAR2(32)  DEFAULT 'TEXT' NOT NULL,
    TEXT_CONTENT        CLOB,
    RESOURCE_URI        VARCHAR2(2048),
    RESOURCE_CHECKSUM   VARCHAR2(128),
    RUNTIME             VARCHAR2(32)  DEFAULT 'PYTHON' NOT NULL,
    PARAMETERS          JSON,
    DEPENDENCIES        JSON,
    SKILL_STATUS        VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    RESOURCE_FILENAME   VARCHAR2(512),
    RESOURCE_SIZE       NUMBER,
    RESOURCE_MIME_TYPE  VARCHAR2(128),
    RESOURCE_SERVER_HOST VARCHAR2(512),
    SKILL_DESCRIPTION   CLOB,
    CONSTRAINT PK_SKILL_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_SKM_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE) ON DELETE CASCADE,
    CONSTRAINT CK_SKM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'SKILL'),
    CONSTRAINT CK_SKM_TYPE CHECK (SKILL_TYPE IN ('BUILTIN','CUSTOM')),
    CONSTRAINT CK_SKM_FORMAT CHECK (SKILL_FORMAT IN ('TEXT','SCRIPT','HYBRID')),
    CONSTRAINT CK_SKM_RUNTIME CHECK (RUNTIME IN ('PYTHON','BASH','NODE','OTHER')),
    CONSTRAINT CK_SKM_STATUS CHECK (SKILL_STATUS IN ('ACTIVE','DEPRECATED','DISABLED'))
) PARTITION BY REFERENCE (FK_SKM_ENTITY);

PROMPT ============================================================
PROMPT 6. TAGS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TAGS (
    TAG_ID    NUMBER(10,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TAG_NAME  VARCHAR2(128) NOT NULL,
    TAG_GROUP VARCHAR2(64),
    CONSTRAINT UK_TAGS_NAME UNIQUE (TAG_NAME)
);

PROMPT ============================================================
PROMPT 7. ENTITY_TAGS (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE ENTITY_TAGS (
    ENTITY_ID   VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE VARCHAR2(32)  NOT NULL,
    TAG_ID      NUMBER(10,0)  NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITY_TAGS PRIMARY KEY (ENTITY_ID, ENTITY_TYPE, TAG_ID),
    CONSTRAINT FK_ET_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE) ON DELETE CASCADE,
    CONSTRAINT FK_ET_TAG FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID)
) PARTITION BY REFERENCE (FK_ET_ENTITY);

PROMPT ============================================================
PROMPT 8. SYSTEM_USERS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE SYSTEM_USERS (
    USER_ID     VARCHAR2(64)  PRIMARY KEY,
    USERNAME    VARCHAR2(128) NOT NULL,
    PASSWORD_HASH VARCHAR2(256),
    ROLE        VARCHAR2(64)  DEFAULT 'USER' NOT NULL,
    STATUS      VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    AUTH_SOURCE VARCHAR2(16)  DEFAULT 'LOCAL' NOT NULL,
    LDAP_DN     VARCHAR2(512),
    LAST_LDAP_SYNC TIMESTAMP,
    LAST_LOGIN  TIMESTAMP,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_SU_ROLE CHECK (ROLE IN ('ADMIN','USER','SERVICE')),
    CONSTRAINT CK_SU_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','LOCKED')),
    CONSTRAINT CK_SU_AUTH_SOURCE CHECK (AUTH_SOURCE IN ('LOCAL','LDAP'))
);

PROMPT ============================================================
PROMPT 9. AGENT_REGISTRY (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE AGENT_REGISTRY (
    AGENT_ID       VARCHAR2(64)  PRIMARY KEY,
    AGENT_NAME     VARCHAR2(256) NOT NULL,
    AGENT_TYPE     VARCHAR2(64),
    DESCRIPTION    VARCHAR2(2000),
    CAPABILITIES   JSON,
    CONFIG         JSON,
    WM_ENTITY_ID   VARCHAR2(64),
    STATUS         VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    LAST_SEEN_AT   TIMESTAMP,
    CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY_AGENT_ID VARCHAR2(64),
    AGENT_ROLE        VARCHAR2(32)  DEFAULT 'WORKER' NOT NULL,
    CURRENT_USER_ID   VARCHAR2(64),
    POOL_CONFIG       JSON,
    LAST_ACTIVE_AT    TIMESTAMP,
    CONSTRAINT CK_APRV_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','SUSPENDED','DECOMMISSIONED','DORMANT','POOL')),
    CONSTRAINT CK_AR_ROLE CHECK (AGENT_ROLE IN ('WORKER','COORDINATOR','SYSTEM')),
    CONSTRAINT FK_AR_CREATED_BY FOREIGN KEY (CREATED_BY_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_AR_CURRENT_USER FOREIGN KEY (CURRENT_USER_ID) REFERENCES SYSTEM_USERS(USER_ID),
    CONSTRAINT FK_AR_WM_ENTITY FOREIGN KEY (WM_ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID)
);


PROMPT ============================================================
PROMPT 9b. AGENT_CREDENTIALS (Non-Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE AGENT_CREDENTIALS (
    CREDENTIAL_ID    VARCHAR2(64)  PRIMARY KEY,
    AGENT_ID         VARCHAR2(64)  NOT NULL,
    USER_ID          VARCHAR2(64)  NOT NULL,
    CREDENTIAL_TYPE  VARCHAR2(32)  NOT NULL,
    CREDENTIAL_VALUE VARCHAR2(512) NOT NULL,
    SCOPE            JSON          NOT NULL,
    EXPIRES_AT       TIMESTAMP,
    IS_ACTIVE        VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_AC_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_AC_USER FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USERS(USER_ID),
    CONSTRAINT CK_AC_TYPE CHECK (CREDENTIAL_TYPE IN ('ACCESS_TOKEN','SESSION_KEY','PASSWORD_HASH')),
    CONSTRAINT CK_AC_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

PROMPT ============================================================
PROMPT 10. WORKSPACES (Non-Partitioned) [NEW v2.2.0]
PROMPT ============================================================

CREATE TABLE WORKSPACES (
    WORKSPACE_ID       VARCHAR2(64)  PRIMARY KEY,
    OWNER_USER_ID      VARCHAR2(64),
    WORKSPACE_NAME     VARCHAR2(256) NOT NULL,
    WORKSPACE_TYPE     VARCHAR2(32)  DEFAULT 'CONVERSATION' NOT NULL,
    STATUS             VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    ISOLATION_MODE     VARCHAR2(16)  DEFAULT 'SHARED' NOT NULL,
    CURRENT_AGENT_ID   VARCHAR2(64),
    CURRENT_SESSION_ID VARCHAR2(64),
    SUMMARY            VARCHAR2(2000),
    METADATA           JSON,
    CREATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    WORKSPACE_ALIAS    VARCHAR2(256),
    CONSTRAINT FK_WS_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES SYSTEM_USERS(USER_ID),
    CONSTRAINT FK_WS_AGENT FOREIGN KEY (CURRENT_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT CK_WS_STATUS CHECK (STATUS IN ('ACTIVE','PAUSED','COMPLETED','ABANDONED')),
    CONSTRAINT CK_WS_TYPE CHECK (WORKSPACE_TYPE IN ('CONVERSATION','PROJECT','TASK_CHAIN','AUTONOMOUS','COLLAB_GROUP','PERSONAL_IN_GROUP')),
    CONSTRAINT CK_WS_ISOLATION CHECK (ISOLATION_MODE IN ('SHARED','ISOLATED'))
);

PROMPT ============================================================
PROMPT 11. WORKSPACE_CONTEXT (Non-Partitioned) [NEW v2.2.0]
PROMPT ============================================================

CREATE TABLE WORKSPACE_CONTEXT (
    CONTEXT_ID        VARCHAR2(64)  PRIMARY KEY,
    WORKSPACE_ID      VARCHAR2(64)  NOT NULL,
    AGENT_ID          VARCHAR2(64)  NOT NULL,
    SESSION_ID        VARCHAR2(64),
    CONTEXT_TYPE      VARCHAR2(32)  NOT NULL,
    CONTEXT_DATA      JSON          NOT NULL,
    PARENT_CONTEXT_ID VARCHAR2(64),
    BRANCH_ID         VARCHAR2(64),
    VISIBILITY        VARCHAR2(20)  DEFAULT 'SHARED' NOT NULL,
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_WC_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_WC_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_WC_PARENT FOREIGN KEY (PARENT_CONTEXT_ID) REFERENCES WORKSPACE_CONTEXT(CONTEXT_ID) ON DELETE SET NULL,
    CONSTRAINT FK_WC_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES CONTEXT_BRANCHES(BRANCH_ID) ON DELETE SET NULL,
    CONSTRAINT CK_WC_TYPE CHECK (CONTEXT_TYPE IN ('CHECKPOINT','HANDOFF','SUMMARY','ERROR_STATE','AUTO_SAVE','CHAT_MESSAGE','BRANCH_POINT')),
    CONSTRAINT CK_WS_CTX_VISIBILITY CHECK (VISIBILITY IN ('PRIVATE', 'SHARED', 'PUBLIC'))
);

PROMPT ============================================================
PROMPT 11c. BRANCH_MERGE_LOG (Non-Partitioned) [NEW v3.3.0]
PROMPT ============================================================

CREATE TABLE BRANCH_MERGE_LOG (
    MERGE_ID         VARCHAR2(64)  PRIMARY KEY,
    SOURCE_BRANCH_ID VARCHAR2(64)  NOT NULL,
    TARGET_BRANCH_ID VARCHAR2(64)  NOT NULL,
    MERGE_TYPE       VARCHAR2(32)  NOT NULL,
    MERGED_BY_AGENT  VARCHAR2(64),
    MERGE_CONTEXT_ID VARCHAR2(64),
    CONFLICTS        JSON,
    MERGE_RESULT     VARCHAR2(32)  DEFAULT 'SUCCESS' NOT NULL,
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_BML_SRC FOREIGN KEY (SOURCE_BRANCH_ID) REFERENCES CONTEXT_BRANCHES(BRANCH_ID),
    CONSTRAINT FK_BML_TGT FOREIGN KEY (TARGET_BRANCH_ID) REFERENCES CONTEXT_BRANCHES(BRANCH_ID),
    CONSTRAINT CK_BML_TYPE CHECK (MERGE_TYPE IN ('MERGE','CHERRY_PICK','REBASE')),
    CONSTRAINT CK_BML_RESULT CHECK (MERGE_RESULT IN ('SUCCESS','PARTIAL','CONFLICT','ABORTED'))
);

PROMPT ============================================================
PROMPT 12. WORKSPACE_TASKS - deferred after TASK_PLANS
PROMPT ============================================================

PROMPT ============================================================
PROMPT 13. AGENT_SESSION (Partitioned by LIST + RANGE)
PROMPT ============================================================

CREATE TABLE AGENT_SESSION (
    SESSION_ID             VARCHAR2(64)  NOT NULL,
    AGENT_ID               VARCHAR2(64)  NOT NULL,
    WM_ENTITY_ID           VARCHAR2(64),
    OWNER_USER_ID          VARCHAR2(64),
    WORKSPACE_ID           VARCHAR2(64),
    PREDECESSOR_SESSION_ID VARCHAR2(64),
    BRANCH_ID              VARCHAR2(64),
    IS_ACTIVE              VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    START_TIME             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    END_TIME               TIMESTAMP,
    CONTEXT                JSON,
    LAST_ACTIVE_AT         TIMESTAMP,
    CONSTRAINT PK_AGENT_SESSION PRIMARY KEY (SESSION_ID, IS_ACTIVE),
    CONSTRAINT CK_AS_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT FK_SESSION_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_SESSION_WM FOREIGN KEY (WM_ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT FK_SESSION_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES SYSTEM_USERS(USER_ID),
    CONSTRAINT FK_SESSION_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID),
    CONSTRAINT FK_SESSION_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES CONTEXT_BRANCHES(BRANCH_ID) ON DELETE SET NULL
) PARTITION BY LIST (IS_ACTIVE)
SUBPARTITION BY RANGE (START_TIME)
SUBPARTITION TEMPLATE (
    SUBPARTITION SP_2026Q1 VALUES LESS THAN (TO_DATE('2026-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q2 VALUES LESS THAN (TO_DATE('2026-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q3 VALUES LESS THAN (TO_DATE('2026-10-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q4 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q1 VALUES LESS THAN (TO_DATE('2027-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q2 VALUES LESS THAN (TO_DATE('2027-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_FUTURE VALUES LESS THAN (MAXVALUE)
)
(
    PARTITION P_ACTIVE    VALUES ('Y'),
    PARTITION P_INACTIVE  VALUES ('N'),
    PARTITION P_OTHER     VALUES (DEFAULT)
);

ALTER TABLE AGENT_SESSION ENABLE ROW MOVEMENT;

ALTER TABLE AGENT_SESSION ADD CONSTRAINT UK_SESSION_ID UNIQUE (SESSION_ID);
ALTER TABLE AGENT_SESSION ADD CONSTRAINT FK_SESSION_PREDECESSOR FOREIGN KEY (PREDECESSOR_SESSION_ID) REFERENCES AGENT_SESSION(SESSION_ID);

PROMPT ============================================================
PROMPT 14. ENTITY_ACCESS_LOG (Partitioned by RANGE + HASH)
PROMPT ============================================================

CREATE TABLE ENTITY_ACCESS_LOG (
    LOG_ID        VARCHAR2(64)  NOT NULL,
    ENTITY_ID     VARCHAR2(64)  NOT NULL,
    AGENT_ID      VARCHAR2(64)  NOT NULL,
    ACCESS_TYPE   VARCHAR2(32)  NOT NULL,
    ACCESS_TIME   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    SESSION_ID    VARCHAR2(64),
    CONTEXT       JSON,
    CONSTRAINT CK_EAL_ACCESS_TYPE CHECK (ACCESS_TYPE IN ('READ','WRITE','DELETE','SEARCH','EMBED'))
) PARTITION BY RANGE (ACCESS_TIME)
SUBPARTITION BY HASH (AGENT_ID) SUBPARTITIONS 4
(
    PARTITION P_202605 VALUES LESS THAN (TO_DATE('2026-06-01','YYYY-MM-DD')),
    PARTITION P_202606 VALUES LESS THAN (TO_DATE('2026-07-01','YYYY-MM-DD')),
    PARTITION P_MAX    VALUES LESS THAN (MAXVALUE)
);

ALTER TABLE ENTITY_ACCESS_LOG ADD CONSTRAINT UK_ACCESS_LOG_ID UNIQUE (LOG_ID);

ALTER TABLE ENTITY_ACCESS_LOG ADD CONSTRAINT FK_EAL_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID);
ALTER TABLE ENTITY_ACCESS_LOG ADD CONSTRAINT FK_EAL_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID);

PROMPT ============================================================
PROMPT 15. AGENT_PERMISSION_LOG (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE AGENT_PERMISSION_LOG (
    LOG_ID        VARCHAR2(64)  PRIMARY KEY,
    AGENT_ID      VARCHAR2(64)  NOT NULL,
    GRANTED_BY    VARCHAR2(64),
    PERMISSION    VARCHAR2(128) NOT NULL,
    RESOURCE_TYPE VARCHAR2(64)  NOT NULL,
    RESOURCE_ID   VARCHAR2(64)  NOT NULL,
    ACTION        VARCHAR2(32)  NOT NULL,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_APL_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT CK_APL_ACTION CHECK (ACTION IN ('GRANT','REVOKE','DENY'))
);

PROMPT ============================================================
PROMPT 16. AGENT_COLLABORATION (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE AGENT_COLLABORATION (
    COL_ID          VARCHAR2(64)  PRIMARY KEY,
    SOURCE_AGENT_ID VARCHAR2(64)  NOT NULL,
    TARGET_AGENT_ID VARCHAR2(64)  NOT NULL,
    COL_TYPE        VARCHAR2(64)  NOT NULL,
    ENTITY_ID       VARCHAR2(64),
    CONTEXT         JSON,
    STRENGTH        NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_COL_SOURCE FOREIGN KEY (SOURCE_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_COL_TARGET FOREIGN KEY (TARGET_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_COL_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT CK_COL_STRENGTH CHECK (STRENGTH BETWEEN 0 AND 1)
);


PROMPT ============================================================
PROMPT 16b. COLLAB_GROUPS (Non-Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE COLLAB_GROUPS (
    GROUP_ID             VARCHAR2(64)  PRIMARY KEY,
    GROUP_NAME           VARCHAR2(256) NOT NULL,
    GROUP_TYPE           VARCHAR2(32)  NOT NULL,
    DESCRIPTION          VARCHAR2(2000),
    WORKSPACE_ID         VARCHAR2(64),
    COORDINATOR_AGENT_ID VARCHAR2(64),
    SHARING_POLICY       VARCHAR2(32)  DEFAULT 'OPEN' NOT NULL,
    STATUS               VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    METADATA             JSON,
    BRANCH_ID            VARCHAR2(64),
    SPEC_ID              VARCHAR2(64),
    CREATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CG_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID),
    CONSTRAINT FK_CG_COORDINATOR FOREIGN KEY (COORDINATOR_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_CG_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES CONTEXT_BRANCHES(BRANCH_ID) ON DELETE SET NULL,
    CONSTRAINT FK_CG_SPEC FOREIGN KEY (SPEC_ID) REFERENCES ENTITIES(ENTITY_ID) ON DELETE SET NULL,
    CONSTRAINT CK_CG_TYPE CHECK (GROUP_TYPE IN ('PROJECT','TEAM','AD_HOC','PIPELINE')),
    CONSTRAINT CK_CG_POLICY CHECK (SHARING_POLICY IN ('OPEN','MODERATED','RESTRICTED')),
    CONSTRAINT CK_CG_STATUS CHECK (STATUS IN ('ACTIVE','PAUSED','ARCHIVED'))
);

PROMPT ============================================================
PROMPT 16c. COLLAB_GROUP_MEMBERS (Non-Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE COLLAB_GROUP_MEMBERS (
    MEMBER_ID               VARCHAR2(64)  PRIMARY KEY,
    GROUP_ID                VARCHAR2(64)  NOT NULL,
    AGENT_ID                VARCHAR2(64)  NOT NULL,
    ROLE                    VARCHAR2(32)  DEFAULT 'MEMBER' NOT NULL,
    PERSONAL_WORKSPACE_ID   VARCHAR2(64),
    BRANCH_ID               VARCHAR2(64),
    JOINED_AT               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS                  VARCHAR2(16)  DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT FK_CGM_GROUP FOREIGN KEY (GROUP_ID) REFERENCES COLLAB_GROUPS(GROUP_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CGM_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_CGM_WORKSPACE FOREIGN KEY (PERSONAL_WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID),
    CONSTRAINT CK_CGM_ROLE CHECK (ROLE IN ('LEAD','MEMBER','OBSERVER','CONTRIBUTOR')),
    CONSTRAINT CK_CGM_STATUS CHECK (STATUS IN ('ACTIVE','LEFT','REMOVED')),
    CONSTRAINT UK_CGM_MEMBERSHIP UNIQUE (GROUP_ID, AGENT_ID)
);

PROMPT ============================================================
PROMPT 17. TASK_PLANS (Partitioned by LIST + RANGE)
PROMPT ============================================================

CREATE TABLE TASK_PLANS (
    PLAN_ID        VARCHAR2(64)   NOT NULL,
    AGENT_ID       VARCHAR2(64)   NOT NULL,
    GOAL           VARCHAR2(2000) NOT NULL,
    STATUS         VARCHAR2(30)   DEFAULT 'PENDING' NOT NULL,
    PRIORITY       NUMBER(3,0)    DEFAULT 5 NOT NULL,
    STRATEGY       VARCHAR2(64),
    RESULT_SUMMARY VARCHAR2(2000),
    BRANCH_ID      VARCHAR2(64),
    CREATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT   TIMESTAMP,
    CONSTRAINT PK_TASK_PLANS PRIMARY KEY (PLAN_ID, STATUS),
    CONSTRAINT CK_TP_STATUS CHECK (STATUS IN ('PENDING','RUNNING','BLOCKED','SUCCESS','FAILED','CANCELLED')),
    CONSTRAINT CK_TP_PRIORITY CHECK (PRIORITY BETWEEN 1 AND 10),
    CONSTRAINT FK_TP_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_TP_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES CONTEXT_BRANCHES(BRANCH_ID) ON DELETE SET NULL
) PARTITION BY LIST (STATUS)
SUBPARTITION BY RANGE (CREATED_AT)
SUBPARTITION TEMPLATE (
    SUBPARTITION SP_2026Q1 VALUES LESS THAN (TO_DATE('2026-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q2 VALUES LESS THAN (TO_DATE('2026-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q3 VALUES LESS THAN (TO_DATE('2026-10-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q4 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q1 VALUES LESS THAN (TO_DATE('2027-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q2 VALUES LESS THAN (TO_DATE('2027-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_FUTURE VALUES LESS THAN (MAXVALUE)
)
(
    PARTITION P_ACTIVE    VALUES ('PENDING','RUNNING','BLOCKED'),
    PARTITION P_TERMINAL  VALUES ('SUCCESS','FAILED','CANCELLED'),
    PARTITION P_OTHER     VALUES (DEFAULT)
);

ALTER TABLE TASK_PLANS ADD CONSTRAINT UK_TASK_PLANS_ID UNIQUE (PLAN_ID);

ALTER TABLE TASK_PLANS ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 18. TASK_STEPS (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_STEPS (
    STEP_ID       VARCHAR2(64)   NOT NULL,
    PLAN_ID       VARCHAR2(64)   NOT NULL,
    PLAN_STATUS   VARCHAR2(30)   NOT NULL,
    STEP_ORDER    NUMBER(5,0)    NOT NULL,
    DESCRIPTION   VARCHAR2(2000) NOT NULL,
    TOOL_NAME     VARCHAR2(128),
    TOOL_INPUT    JSON,
    TOOL_OUTPUT   JSON,
    ASSIGNED_AGENT_ID VARCHAR2(64),
    STATUS        VARCHAR2(30)   DEFAULT 'PENDING' NOT NULL,
    STARTED_AT    TIMESTAMP,
    COMPLETED_AT  TIMESTAMP,
    LOOP_ID       VARCHAR2(64),
    STEP_COMPLETION_TYPE VARCHAR2(20) DEFAULT 'MANUAL',
    CONSTRAINT PK_TASK_STEPS PRIMARY KEY (STEP_ID, PLAN_ID),
    CONSTRAINT FK_STEP_PLAN FOREIGN KEY (PLAN_ID, PLAN_STATUS) REFERENCES TASK_PLANS(PLAN_ID, STATUS),
    CONSTRAINT CK_TS_STATUS CHECK (STATUS IN ('PENDING','RUNNING','BLOCKED','SUCCESS','FAILED','SKIPPED','WAITING_LOOP')),
    CONSTRAINT FK_TS_ASSIGNED_AGENT FOREIGN KEY (ASSIGNED_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_TS_LOOP FOREIGN KEY (LOOP_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT CK_TS_COMPLETION CHECK (STEP_COMPLETION_TYPE IN ('MANUAL','LOOP','SPEC'))
) PARTITION BY REFERENCE (FK_STEP_PLAN) ENABLE ROW MOVEMENT;

ALTER TABLE TASK_STEPS ADD CONSTRAINT UK_TASK_STEPS_ID UNIQUE (STEP_ID);
ALTER TABLE TASK_STEPS ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 19. TASK_CONTEXT_SNAPSHOTS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_CONTEXT_SNAPSHOTS (
    SNAPSHOT_ID   VARCHAR2(64)  PRIMARY KEY,
    PLAN_ID       VARCHAR2(64)  NOT NULL,
    SNAPSHOT_TYPE VARCHAR2(64)  NOT NULL,
    CONTEXT_DATA  JSON,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SNAP_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID)
);

PROMPT ============================================================
PROMPT 20. TASK_TOOL_CALLS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_TOOL_CALLS (
    CALL_ID      VARCHAR2(64)  PRIMARY KEY,
    PLAN_ID      VARCHAR2(64)  NOT NULL,
    STEP_ID      VARCHAR2(64),
    TOOL_NAME    VARCHAR2(128) NOT NULL,
    TOOL_INPUT   JSON,
    TOOL_OUTPUT  JSON,
    STATUS       VARCHAR2(30)  DEFAULT 'PENDING' NOT NULL,
    DURATION_MS  NUMBER(10,0),
    CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_TC_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID),
    CONSTRAINT FK_TC_STEP FOREIGN KEY (STEP_ID) REFERENCES TASK_STEPS(STEP_ID),
    CONSTRAINT CK_TTC_STATUS CHECK (STATUS IN ('PENDING','RUNNING','SUCCESS','FAILED','TIMEOUT'))
);

PROMPT ============================================================
PROMPT 21. TASK_DEPENDENCIES (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_DEPENDENCIES (
    DEP_ID          VARCHAR2(64)  PRIMARY KEY,
    SOURCE_PLAN_ID  VARCHAR2(64)  NOT NULL,
    TARGET_PLAN_ID  VARCHAR2(64)  NOT NULL,
    DEP_TYPE        VARCHAR2(64)  NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DEP_SOURCE FOREIGN KEY (SOURCE_PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID),
    CONSTRAINT FK_DEP_TARGET FOREIGN KEY (TARGET_PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID),
    CONSTRAINT CK_DEP_TYPE CHECK (DEP_TYPE IN ('BLOCKS','DEPENDS_ON','TRIGGERS','RELATES_TO'))
);

PROMPT ============================================================
PROMPT 21a. TASK_LOOP_BINDING (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE TASK_LOOP_BINDING (
    BINDING_ID    VARCHAR2(64)  PRIMARY KEY,
    STEP_ID       VARCHAR2(64)  NOT NULL,
    LOOP_ID       VARCHAR2(64)  NOT NULL,
    BINDING_TYPE  VARCHAR2(20)  DEFAULT 'COMPLETION',
    AUTO_START    VARCHAR2(1)   DEFAULT 'N',
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_TLB_STEP FOREIGN KEY (STEP_ID) REFERENCES TASK_STEPS(STEP_ID),
    CONSTRAINT FK_TLB_LOOP FOREIGN KEY (LOOP_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT CK_TLB_TYPE CHECK (BINDING_TYPE IN ('COMPLETION','VALIDATION')),
    CONSTRAINT CK_TLB_AUTO CHECK (AUTO_START IN ('Y','N'))
);


PROMPT ============================================================
PROMPT 21b. SPEC_PLAN_LINKS (Non-Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE SPEC_PLAN_LINKS (
    LINK_ID        VARCHAR2(64)  PRIMARY KEY,
    SPEC_ID        VARCHAR2(64)  NOT NULL,
    PLAN_ID        VARCHAR2(64)  NOT NULL,
    LINK_TYPE      VARCHAR2(32)  NOT NULL,
    LINK_STRENGTH  NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SPL_SPEC FOREIGN KEY (SPEC_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT FK_SPL_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID),
    CONSTRAINT CK_SPL_TYPE CHECK (LINK_TYPE IN ('DRIVES','VALIDATES','CONSTRAINS','EXTENDS')),
    CONSTRAINT CK_SPL_STRENGTH CHECK (LINK_STRENGTH BETWEEN 0 AND 1),
    CONSTRAINT UK_SPL_LINK UNIQUE (SPEC_ID, PLAN_ID, LINK_TYPE)
);

PROMPT ============================================================
PROMPT 22. WORKSPACE_TASKS (Non-Partitioned) [NEW v2.2.0]
PROMPT ============================================================

CREATE TABLE WORKSPACE_TASKS (
    WORKSPACE_ID  VARCHAR2(64) NOT NULL,
    PLAN_ID       VARCHAR2(64) NOT NULL,
    ASSIGNED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_WORKSPACE_TASKS PRIMARY KEY (WORKSPACE_ID, PLAN_ID),
    CONSTRAINT FK_WT_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_WT_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID)
);







PROMPT ============================================================
PROMPT 23. SYSTEM_CONFIG (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE SYSTEM_CONFIG (
    CONFIG_KEY   VARCHAR2(128) PRIMARY KEY,
    CONFIG_VALUE VARCHAR2(4000) NOT NULL,
    DESCRIPTION  VARCHAR2(2000),
    UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

PROMPT ============================================================
PROMPT 24. LOOP_META (Reference Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE LOOP_META (
    ENTITY_ID           VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE         VARCHAR2(32)  DEFAULT 'LOOP_DEFINITION' NOT NULL,
    LOOP_VERSION        VARCHAR2(32)  DEFAULT '1.0' NOT NULL,
    GOAL_DEFINITION     JSON          NOT NULL,
    STOP_CONDITIONS     JSON          NOT NULL,
    EVALUATION_CONFIG   JSON          NOT NULL,
    TRIGGER_CONFIG      JSON,
    HARNESS_TEMPLATE_ID VARCHAR2(64),
    WORKSPACE_ID        VARCHAR2(64),
    BRANCH_ID           VARCHAR2(64),
    SPEC_ID             VARCHAR2(64),
    PARENT_LOOP_ID      VARCHAR2(64),
    COLLAB_GROUP_ID     VARCHAR2(64),
    CONSTRAINT PK_LOOP_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_LM_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE) ON DELETE CASCADE,
    CONSTRAINT FK_LM_HARNESS FOREIGN KEY (HARNESS_TEMPLATE_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT FK_LM_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID) ON DELETE SET NULL,
    CONSTRAINT FK_LM_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES CONTEXT_BRANCHES(BRANCH_ID) ON DELETE SET NULL,
    CONSTRAINT FK_LM_SPEC FOREIGN KEY (SPEC_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT FK_LM_PARENT_LOOP FOREIGN KEY (PARENT_LOOP_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT FK_LM_COLLAB FOREIGN KEY (COLLAB_GROUP_ID) REFERENCES COLLAB_GROUPS(GROUP_ID),
    CONSTRAINT CK_LM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'LOOP_DEFINITION')
) PARTITION BY REFERENCE (FK_LM_ENTITY);

PROMPT ============================================================
PROMPT 25. LOOP_RUNS (Partitioned by LIST + RANGE) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE LOOP_RUNS (
    RUN_ID            VARCHAR2(64)   NOT NULL,
    LOOP_ID           VARCHAR2(64)   NOT NULL,
    AGENT_ID          VARCHAR2(64)   NOT NULL,
    TRIGGER_TYPE      VARCHAR2(32)   DEFAULT 'MANUAL' NOT NULL,
    TRIGGER_SOURCE    VARCHAR2(256),
    STATUS            VARCHAR2(30)   DEFAULT 'PENDING' NOT NULL,
    ITERATION_COUNT   NUMBER(5,0)    DEFAULT 0 NOT NULL,
    TOTAL_TOKENS      NUMBER(12,0)   DEFAULT 0 NOT NULL,
    FINAL_RESULT      VARCHAR2(4000),
    ERROR_MESSAGE     VARCHAR2(2000),
    STARTED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT      TIMESTAMP,
    PARENT_RUN_ID     VARCHAR2(64),
    CONSTRAINT PK_LOOP_RUNS PRIMARY KEY (RUN_ID, STATUS),
    CONSTRAINT UK_LOOP_RUNS_ID UNIQUE (RUN_ID),
    CONSTRAINT FK_LR_LOOP FOREIGN KEY (LOOP_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT FK_LR_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_LR_PARENT_RUN FOREIGN KEY (PARENT_RUN_ID) REFERENCES LOOP_RUNS(RUN_ID),
    CONSTRAINT CK_LR_STATUS CHECK (STATUS IN ('PENDING','RUNNING','PAUSED','COMPLETED','STOPPED','FAILED','TIMEOUT')),
    CONSTRAINT CK_LR_TRIGGER CHECK (TRIGGER_TYPE IN ('MANUAL','SCHEDULE','EVENT','HOOK'))
) PARTITION BY LIST (STATUS)
SUBPARTITION BY RANGE (STARTED_AT)
SUBPARTITION TEMPLATE (
    SUBPARTITION SP_2026Q3 VALUES LESS THAN (TO_DATE('2026-10-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q4 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q1 VALUES LESS THAN (TO_DATE('2027-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q2 VALUES LESS THAN (TO_DATE('2027-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q3 VALUES LESS THAN (TO_DATE('2027-10-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q4 VALUES LESS THAN (TO_DATE('2028-01-01','YYYY-MM-DD')),
    SUBPARTITION SP_FUTURE VALUES LESS THAN (MAXVALUE)
)
(
    PARTITION P_ACTIVE    VALUES ('PENDING','RUNNING','PAUSED'),
    PARTITION P_TERMINAL  VALUES ('COMPLETED','STOPPED','FAILED','TIMEOUT'),
    PARTITION P_OTHER     VALUES (DEFAULT)
);

ALTER TABLE LOOP_RUNS ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 26. LOOP_ITERATIONS (Reference Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE LOOP_ITERATIONS (
    ITERATION_ID      VARCHAR2(64)   NOT NULL,
    RUN_ID            VARCHAR2(64)   NOT NULL,
    ITERATION_ORDER   NUMBER(5,0)    NOT NULL,
    PLAN_DATA         JSON,
    ACTIONS           JSON,
    OBSERVATIONS      JSON,
    EVALUATION_RESULT JSON,
    EVALUATION_PASSED VARCHAR2(1)    DEFAULT 'N' NOT NULL,
    ADJUSTMENT        JSON,
    TOKEN_USAGE       NUMBER(12,0)   DEFAULT 0 NOT NULL,
    STARTED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT      TIMESTAMP,
    CONSTRAINT PK_LOOP_ITERATIONS PRIMARY KEY (ITERATION_ID, RUN_ID),
    CONSTRAINT FK_LI_RUN FOREIGN KEY (RUN_ID) REFERENCES LOOP_RUNS(RUN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_LI_PASSED CHECK (EVALUATION_PASSED IN ('Y','N'))
) PARTITION BY RANGE (STARTED_AT)
(
    PARTITION PI_2026Q3 VALUES LESS THAN (TO_DATE('2026-10-01','YYYY-MM-DD')),
    PARTITION PI_2026Q4 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    PARTITION PI_2027Q1 VALUES LESS THAN (TO_DATE('2027-04-01','YYYY-MM-DD')),
    PARTITION PI_2027Q2 VALUES LESS THAN (TO_DATE('2027-07-01','YYYY-MM-DD')),
    PARTITION PI_2027Q3 VALUES LESS THAN (TO_DATE('2027-10-01','YYYY-MM-DD')),
    PARTITION PI_2027Q4 VALUES LESS THAN (TO_DATE('2028-01-01','YYYY-MM-DD')),
    PARTITION PI_FUTURE VALUES LESS THAN (MAXVALUE)
);

ALTER TABLE LOOP_ITERATIONS ADD CONSTRAINT UK_LOOP_ITER_ID UNIQUE (ITERATION_ID);
ALTER TABLE LOOP_ITERATIONS ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 27. LOOP_HOOKS (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE LOOP_HOOKS (
    HOOK_ID       VARCHAR2(64)  PRIMARY KEY,
    LOOP_ID       VARCHAR2(64)  NOT NULL,
    HOOK_EVENT    VARCHAR2(32)  NOT NULL,
    HOOK_TYPE     VARCHAR2(32)  NOT NULL,
    HOOK_CONFIG   JSON,
    PRIORITY      NUMBER(3,0)   DEFAULT 5 NOT NULL,
    ENABLED       VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_LH_LOOP FOREIGN KEY (LOOP_ID) REFERENCES ENTITIES(ENTITY_ID) ON DELETE CASCADE,
    CONSTRAINT CK_LH_EVENT CHECK (HOOK_EVENT IN ('PRE_RUN','POST_ITERATION','ON_STOP','ON_FAIL','ON_TIMEOUT','ON_START')),
    CONSTRAINT CK_LH_TYPE CHECK (HOOK_TYPE IN ('WEBHOOK','SCRIPT','NOTIFICATION','LOG','MCP_CALL')),
    CONSTRAINT CK_LH_ENABLED CHECK (ENABLED IN ('Y','N')),
    CONSTRAINT CK_LH_PRIORITY CHECK (PRIORITY BETWEEN 1 AND 10)
);


PROMPT ============================================================
PROMPT Local Indexes on ENTITIES
PROMPT ============================================================

CREATE INDEX IDX_ENTITIES_CATEGORY ON ENTITIES(CATEGORY) LOCAL;
CREATE INDEX IDX_ENTITIES_STATUS ON ENTITIES(STATUS) LOCAL;
CREATE INDEX IDX_ENTITIES_OWNED_BY ON ENTITIES(OWNED_BY_AGENT) LOCAL;
CREATE INDEX IDX_ENTITIES_VISIBILITY ON ENTITIES(VISIBILITY) LOCAL;
CREATE INDEX IDX_ENTITIES_WORKSPACE ON ENTITIES(WORKSPACE_ID) LOCAL;

PROMPT ============================================================
PROMPT Local Indexes on ENTITY_EDGES
PROMPT ============================================================

CREATE INDEX IDX_EDGES_TARGET ON ENTITY_EDGES(TARGET_ID) LOCAL;
CREATE INDEX IDX_EDGES_TYPE ON ENTITY_EDGES(EDGE_TYPE) LOCAL;
CREATE INDEX IDX_EDGES_TARGET_TYPE ON ENTITY_EDGES(TARGET_ID, EDGE_TYPE) LOCAL;

PROMPT ============================================================
PROMPT Other Indexes
PROMPT ============================================================

CREATE INDEX IDX_KM_DOMAIN ON KNOWLEDGE_META(DOMAIN) LOCAL;
CREATE INDEX IDX_KM_TOPIC ON KNOWLEDGE_META(TOPIC) LOCAL;
CREATE INDEX IDX_KM_NEXT_REVIEW ON KNOWLEDGE_META(NEXT_REVIEW) LOCAL;

CREATE INDEX IDX_EE_MODEL ON ENTITY_EMBEDDINGS(EMBEDDING_MODEL) LOCAL;

CREATE INDEX IDX_ET_TAG ON ENTITY_TAGS(TAG_ID) LOCAL;

CREATE INDEX IDX_AR_STATUS ON AGENT_REGISTRY(STATUS);
CREATE INDEX IDX_AR_TYPE ON AGENT_REGISTRY(AGENT_TYPE);

CREATE INDEX IDX_AS_AGENT ON AGENT_SESSION(AGENT_ID) LOCAL;

CREATE INDEX IDX_EAL_ENTITY ON ENTITY_ACCESS_LOG(ENTITY_ID) LOCAL;
CREATE INDEX IDX_EAL_TIME ON ENTITY_ACCESS_LOG(ACCESS_TIME) LOCAL;

CREATE INDEX IDX_APL_AGENT ON AGENT_PERMISSION_LOG(AGENT_ID);

CREATE INDEX IDX_COL_SOURCE ON AGENT_COLLABORATION(SOURCE_AGENT_ID);
CREATE INDEX IDX_COL_TARGET ON AGENT_COLLABORATION(TARGET_AGENT_ID);

CREATE INDEX IDX_TP_AGENT ON TASK_PLANS(AGENT_ID) LOCAL;
CREATE INDEX IDX_TP_BRANCH ON TASK_PLANS(BRANCH_ID);
CREATE INDEX IDX_TS_PLAN ON TASK_STEPS(PLAN_ID) LOCAL;
CREATE INDEX IDX_TS_ASSIGNED_AGENT ON TASK_STEPS(ASSIGNED_AGENT_ID);

CREATE INDEX IDX_TCS_PLAN ON TASK_CONTEXT_SNAPSHOTS(PLAN_ID);
CREATE INDEX IDX_TTC_PLAN ON TASK_TOOL_CALLS(PLAN_ID);
CREATE INDEX IDX_TTC_STEP ON TASK_TOOL_CALLS(STEP_ID);

CREATE INDEX IDX_TD_SOURCE ON TASK_DEPENDENCIES(SOURCE_PLAN_ID);
CREATE INDEX IDX_TD_TARGET ON TASK_DEPENDENCIES(TARGET_PLAN_ID);

ALTER TABLE ENTITIES ADD CONSTRAINT FK_ENTITIES_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID);

ALTER TABLE CONTEXT_BRANCHES ADD CONSTRAINT FK_CB_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID) ON DELETE CASCADE;
ALTER TABLE CONTEXT_BRANCHES ADD CONSTRAINT FK_CB_FORK_CTX FOREIGN KEY (FORK_CONTEXT_ID) REFERENCES WORKSPACE_CONTEXT(CONTEXT_ID) ON DELETE SET NULL;
ALTER TABLE CONTEXT_BRANCHES ADD CONSTRAINT FK_CB_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID);
ALTER TABLE CONTEXT_BRANCHES ADD CONSTRAINT FK_CB_SRC_AGENT FOREIGN KEY (SOURCE_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID);

CREATE INDEX IDX_WS_OWNER ON WORKSPACES(OWNER_USER_ID);
CREATE INDEX IDX_WS_STATUS ON WORKSPACES(STATUS);
CREATE INDEX IDX_WS_ALIAS ON WORKSPACES(WORKSPACE_ALIAS);

CREATE INDEX IDX_WC_WORKSPACE ON WORKSPACE_CONTEXT(WORKSPACE_ID);
CREATE INDEX IDX_WC_AGENT ON WORKSPACE_CONTEXT(AGENT_ID);
CREATE INDEX IDX_WC_TYPE ON WORKSPACE_CONTEXT(CONTEXT_TYPE);
CREATE INDEX IDX_WC_VISIBILITY ON WORKSPACE_CONTEXT(VISIBILITY);

CREATE INDEX IDX_AS_WORKSPACE ON AGENT_SESSION(WORKSPACE_ID) LOCAL;
CREATE INDEX IDX_AS_PREDECESSOR ON AGENT_SESSION(PREDECESSOR_SESSION_ID) LOCAL;
CREATE INDEX IDX_AS_OWNER ON AGENT_SESSION(OWNER_USER_ID) LOCAL;


CREATE INDEX IDX_SM_SCOPE ON SPEC_META(SPEC_SCOPE) LOCAL;
CREATE INDEX IDX_SM_STATUS ON SPEC_META(SPEC_STATUS) LOCAL;
CREATE INDEX IDX_SM_PARENT ON SPEC_META(PARENT_SPEC_ID) LOCAL;
CREATE INDEX IDX_SM_BRANCH ON SPEC_META(BRANCH_ID);

CREATE INDEX IDX_SPL_SPEC ON SPEC_PLAN_LINKS(SPEC_ID);
CREATE INDEX IDX_SPL_PLAN ON SPEC_PLAN_LINKS(PLAN_ID);

CREATE INDEX IDX_AC_AGENT ON AGENT_CREDENTIALS(AGENT_ID);
CREATE INDEX IDX_AC_USER ON AGENT_CREDENTIALS(USER_ID);
CREATE INDEX IDX_AC_ACTIVE ON AGENT_CREDENTIALS(IS_ACTIVE);

CREATE INDEX IDX_CG_WORKSPACE ON COLLAB_GROUPS(WORKSPACE_ID);
CREATE INDEX IDX_CG_STATUS ON COLLAB_GROUPS(STATUS);
CREATE INDEX IDX_CG_TYPE ON COLLAB_GROUPS(GROUP_TYPE);

CREATE INDEX IDX_CGM_GROUP ON COLLAB_GROUP_MEMBERS(GROUP_ID);
CREATE INDEX IDX_CGM_AGENT ON COLLAB_GROUP_MEMBERS(AGENT_ID);

CREATE INDEX IDX_AR_ROLE ON AGENT_REGISTRY(AGENT_ROLE);
CREATE INDEX IDX_AR_USER ON AGENT_REGISTRY(CURRENT_USER_ID);
CREATE INDEX IDX_AR_CREATED_BY ON AGENT_REGISTRY(CREATED_BY_AGENT_ID);








CREATE INDEX IDX_SKM_NAME ON SKILL_META(SKILL_NAME) LOCAL;
CREATE INDEX IDX_SKM_TYPE ON SKILL_META(SKILL_TYPE) LOCAL;
CREATE INDEX IDX_SKM_STATUS ON SKILL_META(SKILL_STATUS) LOCAL;
CREATE INDEX IDX_SKM_RUNTIME ON SKILL_META(RUNTIME) LOCAL;

















CREATE INDEX IDX_CB_WORKSPACE ON CONTEXT_BRANCHES(WORKSPACE_ID);
CREATE INDEX IDX_CB_PARENT ON CONTEXT_BRANCHES(PARENT_BRANCH_ID);
CREATE INDEX IDX_CB_FORK_CTX ON CONTEXT_BRANCHES(FORK_CONTEXT_ID);
CREATE INDEX IDX_CB_AGENT ON CONTEXT_BRANCHES(AGENT_ID);
CREATE INDEX IDX_CB_STATUS ON CONTEXT_BRANCHES(BRANCH_STATUS);
CREATE INDEX IDX_CB_TYPE ON CONTEXT_BRANCHES(BRANCH_TYPE);

CREATE INDEX IDX_WC_BRANCH ON WORKSPACE_CONTEXT(BRANCH_ID);

CREATE INDEX IDX_BML_SRC ON BRANCH_MERGE_LOG(SOURCE_BRANCH_ID);
CREATE INDEX IDX_BML_TGT ON BRANCH_MERGE_LOG(TARGET_BRANCH_ID);
CREATE INDEX IDX_BML_RESULT ON BRANCH_MERGE_LOG(MERGE_RESULT);

CREATE INDEX IDX_LR_LOOP ON LOOP_RUNS(LOOP_ID) LOCAL;
CREATE INDEX IDX_LR_AGENT ON LOOP_RUNS(AGENT_ID) LOCAL;
CREATE INDEX IDX_LR_STATUS ON LOOP_RUNS(STATUS) LOCAL;

CREATE INDEX IDX_LI_RUN ON LOOP_ITERATIONS(RUN_ID) LOCAL;
CREATE INDEX IDX_LI_ORDER ON LOOP_ITERATIONS(ITERATION_ORDER) LOCAL;

CREATE INDEX IDX_LH_LOOP ON LOOP_HOOKS(LOOP_ID);
CREATE INDEX IDX_LH_EVENT ON LOOP_HOOKS(HOOK_EVENT);
CREATE INDEX IDX_LH_ENABLED ON LOOP_HOOKS(ENABLED);

PROMPT ============================================================
PROMPT Property Graph: ORACLE_MEMORY_GRAPH
PROMPT ============================================================

CREATE PROPERTY GRAPH ORACLE_MEMORY_GRAPH
  VERTEX TABLES (
    ENTITIES
      KEY (ENTITY_ID, ENTITY_TYPE)
      PROPERTIES (ENTITY_ID, ENTITY_TYPE, TITLE, CATEGORY, STATUS, OWNED_BY_AGENT, VISIBILITY, IMPORTANCE, CREATED_AT, UPDATED_AT)
  )
  EDGE TABLES (
    ENTITY_EDGES
      KEY (EDGE_ID, SOURCE_ID)
      SOURCE KEY (SOURCE_ID, SOURCE_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE)
      DESTINATION KEY (TARGET_ID) REFERENCES ENTITIES(ENTITY_ID)
      PROPERTIES (EDGE_ID, EDGE_TYPE, STRENGTH, CONFIDENCE, CREATED_AT)
  );

PROMPT ============================================================
PROMPT View: BRANCH_COMPARISON [NEW v3.3.0]
PROMPT ============================================================

CREATE OR REPLACE VIEW BRANCH_COMPARISON AS
SELECT
    b1.BRANCH_ID AS BRANCH_A,
    b2.BRANCH_ID AS BRANCH_B,
    b1.FORK_CONTEXT_ID AS COMMON_ANCESTOR,
    b1.WORKSPACE_ID,
    (SELECT COUNT(*) FROM WORKSPACE_CONTEXT wc WHERE wc.BRANCH_ID = b1.BRANCH_ID) AS CTX_COUNT_A,
    (SELECT COUNT(*) FROM WORKSPACE_CONTEXT wc WHERE wc.BRANCH_ID = b2.BRANCH_ID) AS CTX_COUNT_B,
    b1.AGENT_ID AS AGENT_A,
    b2.AGENT_ID AS AGENT_B,
    b1.BRANCH_TYPE AS TYPE_A,
    b2.BRANCH_TYPE AS TYPE_B,
    b1.BRANCH_STATUS AS STATUS_A,
    b2.BRANCH_STATUS AS STATUS_B
FROM CONTEXT_BRANCHES b1
JOIN CONTEXT_BRANCHES b2 ON b1.WORKSPACE_ID = b2.WORKSPACE_ID
    AND b1.FORK_CONTEXT_ID = b2.FORK_CONTEXT_ID
    AND b1.BRANCH_ID < b2.BRANCH_ID;

PROMPT ============================================================
PROMPT JSON-Relational Duality View: MEMORY_DV (Updatable)
PROMPT ============================================================

CREATE JSON RELATIONAL DUALITY VIEW MEMORY_DV AS
SELECT JSON {
    '_id'          : JSON {'entity_id': e.ENTITY_ID, 'entity_type': e.ENTITY_TYPE},
    'title'        : e.TITLE WITH UPDATE,
    'content'      : e.CONTENT WITH UPDATE,
    'summary'      : e.SUMMARY WITH UPDATE,
    'category'     : e.CATEGORY WITH UPDATE,
    'status'       : e.STATUS WITH UPDATE,
    'owned_by'     : e.OWNED_BY_AGENT WITH UPDATE,
    'source_agent' : e.SOURCE_AGENT WITH UPDATE,
    'visibility'   : e.VISIBILITY WITH UPDATE,
    'importance'   : e.IMPORTANCE WITH UPDATE,
    'workspace_id' : e.WORKSPACE_ID WITH UPDATE,
    'created_at'   : e.CREATED_AT,
    'updated_at'   : e.UPDATED_AT,
    'edges' : [
        SELECT JSON {
            'edge_id'    : eg.EDGE_ID,
            'source_id'  : eg.SOURCE_ID,
            'edge_type'  : eg.EDGE_TYPE WITH UPDATE,
            'target_id'  : eg.TARGET_ID WITH UPDATE,
            'strength'   : eg.STRENGTH WITH UPDATE,
            'confidence' : eg.CONFIDENCE WITH UPDATE
        }
        FROM ENTITY_EDGES eg WITH INSERT UPDATE DELETE
        WHERE eg.SOURCE_ID = e.ENTITY_ID AND eg.SOURCE_TYPE = e.ENTITY_TYPE
    ],
    'tags' : [
        SELECT JSON {
            'entity_id'   : et.ENTITY_ID,
            'entity_type' : et.ENTITY_TYPE,
            'tag_id'      : et.TAG_ID
        }
        FROM ENTITY_TAGS et WITH INSERT DELETE
        WHERE et.ENTITY_ID = e.ENTITY_ID AND et.ENTITY_TYPE = e.ENTITY_TYPE
    ]
}
FROM ENTITIES e WITH INSERT UPDATE DELETE;

PROMPT ============================================================
PROMPT JSON-Relational Duality View: KNOWLEDGE_DV (Updatable)
PROMPT ============================================================

CREATE JSON RELATIONAL DUALITY VIEW KNOWLEDGE_DV AS
SELECT JSON {
    '_id'           : JSON {'entity_id': e.ENTITY_ID, 'entity_type': e.ENTITY_TYPE},
    'title'         : e.TITLE WITH UPDATE,
    'content'       : e.CONTENT WITH UPDATE,
    'summary'       : e.SUMMARY WITH UPDATE,
    'category'      : e.CATEGORY WITH UPDATE,
    'status'        : e.STATUS WITH UPDATE,
    'visibility'    : e.VISIBILITY WITH UPDATE,
    'importance'    : e.IMPORTANCE WITH UPDATE,
    'workspace_id'  : e.WORKSPACE_ID WITH UPDATE,
    'created_at'    : e.CREATED_AT,
    'updated_at'    : e.UPDATED_AT,
    'knowledge_meta' : [
        SELECT JSON {
            'entity_id'     : km.ENTITY_ID,
            'entity_type'   : km.ENTITY_TYPE,
            'domain'        : km.DOMAIN WITH UPDATE,
            'topic'         : km.TOPIC WITH UPDATE,
            'difficulty'    : km.DIFFICULTY WITH UPDATE,
            'review_count'  : km.REVIEW_COUNT WITH UPDATE,
            'last_reviewed' : km.LAST_REVIEWED,
            'next_review'   : km.NEXT_REVIEW
        }
        FROM KNOWLEDGE_META km WITH INSERT UPDATE DELETE
        WHERE km.ENTITY_ID = e.ENTITY_ID AND km.ENTITY_TYPE = e.ENTITY_TYPE
    ],
    'edges' : [
        SELECT JSON {
            'edge_id'    : eg.EDGE_ID,
            'source_id'  : eg.SOURCE_ID,
            'edge_type'  : eg.EDGE_TYPE WITH UPDATE,
            'target_id'  : eg.TARGET_ID WITH UPDATE,
            'strength'   : eg.STRENGTH WITH UPDATE,
            'confidence' : eg.CONFIDENCE WITH UPDATE
        }
        FROM ENTITY_EDGES eg WITH INSERT UPDATE DELETE
        WHERE eg.SOURCE_ID = e.ENTITY_ID AND eg.SOURCE_TYPE = e.ENTITY_TYPE
    ],
    'tags' : [
        SELECT JSON {
            'entity_id'   : et.ENTITY_ID,
            'entity_type' : et.ENTITY_TYPE,
            'tag_id'      : et.TAG_ID
        }
        FROM ENTITY_TAGS et WITH INSERT DELETE
        WHERE et.ENTITY_ID = e.ENTITY_ID AND et.ENTITY_TYPE = e.ENTITY_TYPE
    ]
}
FROM ENTITIES e WITH INSERT UPDATE DELETE;

PROMPT ============================================================
PROMPT JSON-Relational Duality View: WORKSPACE_DV (Updatable) [NEW v2.2.0]
PROMPT ============================================================

CREATE JSON RELATIONAL DUALITY VIEW WORKSPACE_DV AS
SELECT JSON {
    '_id'             : w.WORKSPACE_ID,
    'name'            : w.WORKSPACE_NAME WITH UPDATE,
    'type'            : w.WORKSPACE_TYPE WITH UPDATE,
    'status'          : w.STATUS WITH UPDATE,
    'isolation_mode'  : w.ISOLATION_MODE WITH UPDATE,
    'owner_user_id'   : w.OWNER_USER_ID WITH UPDATE,
    'current_agent'   : w.CURRENT_AGENT_ID WITH UPDATE,
    'summary'         : w.SUMMARY WITH UPDATE,
    'metadata'        : w.METADATA WITH UPDATE,
    'created_at'      : w.CREATED_AT,
    'updated_at'      : w.UPDATED_AT,
    'tasks' : [
        SELECT JSON {
            'workspace_id' : wt.WORKSPACE_ID,
            'plan_id'      : wt.PLAN_ID,
            'assigned_at'  : wt.ASSIGNED_AT
        }
        FROM WORKSPACE_TASKS wt WITH INSERT UPDATE DELETE
        WHERE wt.WORKSPACE_ID = w.WORKSPACE_ID
    ]
}
FROM WORKSPACES w WITH INSERT UPDATE DELETE;

PROMPT ============================================================
PROMPT JSON-Relational Duality View: CONTEXT_DV (Read-Only) [NEW v2.2.0]
PROMPT ============================================================

CREATE JSON RELATIONAL DUALITY VIEW CONTEXT_DV AS
SELECT JSON {
    '_id'        : c.CONTEXT_ID,
    'workspace'  : c.WORKSPACE_ID,
    'agent'      : c.AGENT_ID,
    'session'    : c.SESSION_ID,
    'type'       : c.CONTEXT_TYPE,
    'data'       : c.CONTEXT_DATA,
    'parent'     : c.PARENT_CONTEXT_ID,
    'branch_id'  : c.BRANCH_ID,
    'created_at' : c.CREATED_AT
}
FROM WORKSPACE_CONTEXT c;


PROMPT ============================================================
PROMPT JSON-Relational Duality View: SPEC_DV (Updatable) [NEW v2.3.0]
PROMPT ============================================================

CREATE JSON RELATIONAL DUALITY VIEW SPEC_DV AS
SELECT JSON {
    '_id'                : JSON {'entity_id': e.ENTITY_ID, 'entity_type': e.ENTITY_TYPE},
    'title'              : e.TITLE WITH UPDATE,
    'content'            : e.CONTENT WITH UPDATE,
    'summary'            : e.SUMMARY WITH UPDATE,
    'category'           : e.CATEGORY WITH UPDATE,
    'status'             : e.STATUS WITH UPDATE,
    'owned_by'           : e.OWNED_BY_AGENT WITH UPDATE,
    'visibility'         : e.VISIBILITY WITH UPDATE,
    'importance'         : e.IMPORTANCE WITH UPDATE,
    'workspace_id'       : e.WORKSPACE_ID WITH UPDATE,
    'created_at'         : e.CREATED_AT,
    'updated_at'         : e.UPDATED_AT,
    'spec_meta' : [
        SELECT JSON {
            'entity_id'           : sm.ENTITY_ID,
            'entity_type'         : sm.ENTITY_TYPE,
            'spec_version'        : sm.SPEC_VERSION WITH UPDATE,
            'spec_status'         : sm.SPEC_STATUS WITH UPDATE,
            'acceptance_criteria' : sm.ACCEPTANCE_CRITERIA WITH UPDATE,
            'constraints'         : sm."CONSTRAINTS" WITH UPDATE,
            'spec_scope'          : sm.SPEC_SCOPE WITH UPDATE,
            'complexity'          : sm.COMPLEXITY WITH UPDATE,
            'parent_spec_id'      : sm.PARENT_SPEC_ID WITH UPDATE
        }
        FROM SPEC_META sm WITH INSERT UPDATE DELETE
        WHERE sm.ENTITY_ID = e.ENTITY_ID AND sm.ENTITY_TYPE = e.ENTITY_TYPE
    ],
    'plan_links' : [
        SELECT JSON {
            'link_id'       : spl.LINK_ID,
            'spec_id'       : spl.SPEC_ID,
            'plan_id'       : spl.PLAN_ID WITH UPDATE,
            'link_type'     : spl.LINK_TYPE WITH UPDATE,
            'link_strength' : spl.LINK_STRENGTH WITH UPDATE,
            'created_at'    : spl.CREATED_AT
        }
        FROM SPEC_PLAN_LINKS spl WITH INSERT UPDATE DELETE
        WHERE spl.SPEC_ID = e.ENTITY_ID
    ]
}
FROM ENTITIES e WITH INSERT UPDATE DELETE;

PROMPT ============================================================
PROMPT JSON-Relational Duality View: COLLAB_GROUP_DV (Updatable) [NEW v2.3.0]
PROMPT ============================================================

CREATE JSON RELATIONAL DUALITY VIEW COLLAB_GROUP_DV AS
SELECT JSON {
    '_id'              : g.GROUP_ID,
    'name'             : g.GROUP_NAME WITH UPDATE,
    'type'             : g.GROUP_TYPE WITH UPDATE,
    'description'      : g.DESCRIPTION WITH UPDATE,
    'workspace_id'     : g.WORKSPACE_ID WITH UPDATE,
    'coordinator'      : g.COORDINATOR_AGENT_ID WITH UPDATE,
    'sharing_policy'   : g.SHARING_POLICY WITH UPDATE,
    'status'           : g.STATUS WITH UPDATE,
    'metadata'         : g.METADATA WITH UPDATE,
    'created_at'       : g.CREATED_AT,
    'updated_at'       : g.UPDATED_AT,
    'members' : [
        SELECT JSON {
            'member_id'     : m.MEMBER_ID,
            'group_id'      : m.GROUP_ID,
            'agent_id'      : m.AGENT_ID WITH UPDATE,
            'role'          : m.ROLE WITH UPDATE,
            'workspace_id'  : m.PERSONAL_WORKSPACE_ID WITH UPDATE,
            'joined_at'     : m.JOINED_AT,
            'status'        : m.STATUS WITH UPDATE
        }
        FROM COLLAB_GROUP_MEMBERS m WITH INSERT UPDATE DELETE
        WHERE m.GROUP_ID = g.GROUP_ID
    ]
}
FROM COLLAB_GROUPS g WITH INSERT UPDATE DELETE;

PROMPT ============================================================
PROMPT JSON-Relational Duality View: SKILL_DV (Updatable) [NEW v3.1.0]
PROMPT ============================================================

CREATE JSON RELATIONAL DUALITY VIEW SKILL_DV AS
SELECT JSON {
    '_id'                : JSON {'entity_id': e.ENTITY_ID, 'entity_type': e.ENTITY_TYPE},
    'title'              : e.TITLE WITH UPDATE,
    'content'            : e.CONTENT WITH UPDATE,
    'summary'            : e.SUMMARY WITH UPDATE,
    'category'           : e.CATEGORY WITH UPDATE,
    'status'             : e.STATUS WITH UPDATE,
    'owned_by'           : e.OWNED_BY_AGENT WITH UPDATE,
    'visibility'         : e.VISIBILITY WITH UPDATE,
    'importance'         : e.IMPORTANCE WITH UPDATE,
    'workspace_id'       : e.WORKSPACE_ID WITH UPDATE,
    'created_at'         : e.CREATED_AT,
    'updated_at'         : e.UPDATED_AT,
    'skill_meta' : [
        SELECT JSON {
            'entity_id'          : skm.ENTITY_ID,
            'entity_type'        : skm.ENTITY_TYPE,
            'skill_name'         : skm.SKILL_NAME WITH UPDATE,
            'skill_version'      : skm.SKILL_VERSION WITH UPDATE,
            'skill_type'         : skm.SKILL_TYPE WITH UPDATE,
            'skill_format'       : skm.SKILL_FORMAT WITH UPDATE,
            'resource_uri'       : skm.RESOURCE_URI WITH UPDATE,
            'resource_filename'  : skm.RESOURCE_FILENAME WITH UPDATE,
            'resource_size'      : skm.RESOURCE_SIZE WITH UPDATE,
            'resource_mime_type' : skm.RESOURCE_MIME_TYPE WITH UPDATE,
            'resource_checksum'  : skm.RESOURCE_CHECKSUM WITH UPDATE,
            'resource_server_host' : skm.RESOURCE_SERVER_HOST WITH UPDATE,
            'skill_description'  : skm.SKILL_DESCRIPTION WITH UPDATE,
            'runtime'            : skm.RUNTIME WITH UPDATE,
            'parameters'         : skm.PARAMETERS WITH UPDATE,
            'dependencies'       : skm.DEPENDENCIES WITH UPDATE,
            'skill_status'       : skm.SKILL_STATUS WITH UPDATE
        }
        FROM SKILL_META skm WITH INSERT UPDATE DELETE
        WHERE skm.ENTITY_ID = e.ENTITY_ID AND skm.ENTITY_TYPE = e.ENTITY_TYPE
    ],
    'tags' : [
        SELECT JSON {
            'entity_id'   : et.ENTITY_ID,
            'entity_type' : et.ENTITY_TYPE,
            'tag_id'      : et.TAG_ID
        }
        FROM ENTITY_TAGS et WITH INSERT DELETE
        WHERE et.ENTITY_ID = e.ENTITY_ID AND et.ENTITY_TYPE = e.ENTITY_TYPE
    ]
}
FROM ENTITIES e WITH INSERT UPDATE DELETE;

PROMPT ============================================================
PROMPT v3.7.5 Extensions: Agent Communication, Orchestration, Events, Observability, Tools
PROMPT ============================================================

-- D5: Add TRACE_ID columns for distributed tracing
ALTER TABLE AGENT_SESSION ADD (TRACE_ID VARCHAR2(64));
CREATE INDEX IDX_AS_TRACE ON AGENT_SESSION(TRACE_ID) LOCAL;

ALTER TABLE TASK_PLANS ADD (TRACE_ID VARCHAR2(64));
CREATE INDEX IDX_TP_TRACE ON TASK_PLANS(TRACE_ID) LOCAL;

ALTER TABLE LOOP_RUNS ADD (TRACE_ID VARCHAR2(64));
CREATE INDEX IDX_LR_TRACE ON LOOP_RUNS(TRACE_ID) LOCAL;

ALTER TABLE TASK_TOOL_CALLS ADD (TRACE_ID VARCHAR2(64));
ALTER TABLE TASK_TOOL_CALLS ADD (PARENT_TOOL_CALL_ID VARCHAR2(64) REFERENCES TASK_TOOL_CALLS(CALL_ID));
CREATE INDEX IDX_TTC_TRACE ON TASK_TOOL_CALLS(TRACE_ID);
CREATE INDEX IDX_TTC_PARENT ON TASK_TOOL_CALLS(PARENT_TOOL_CALL_ID);

ALTER TABLE ENTITY_ACCESS_LOG ADD (TRACE_ID VARCHAR2(64));
ALTER TABLE ENTITY_ACCESS_LOG ADD (DURATION_MS NUMBER(10,0));
CREATE INDEX IDX_EAL_TRACE ON ENTITY_ACCESS_LOG(TRACE_ID) LOCAL;

ALTER TABLE WORKSPACE_CONTEXT ADD (TRACE_ID VARCHAR2(64));

-- D6: Extend HARNESS_META with tool registry columns
ALTER TABLE HARNESS_META ADD (TOOL_SOURCE VARCHAR2(32));
ALTER TABLE HARNESS_META ADD (TOOL_NAMESPACE VARCHAR2(64));
ALTER TABLE HARNESS_META ADD (TOOL_VERSION VARCHAR2(32));
ALTER TABLE HARNESS_META ADD (INPUT_SCHEMA JSON);
ALTER TABLE HARNESS_META ADD (OUTPUT_SCHEMA JSON);
ALTER TABLE HARNESS_META ADD (TOOL_ENABLED VARCHAR2(1) DEFAULT 'Y');
CREATE INDEX IDX_HM_NS ON HARNESS_META(TOOL_NAMESPACE);
CREATE INDEX IDX_HM_SOURCE ON HARNESS_META(TOOL_SOURCE);

PROMPT ============================================================
PROMPT 35. COLLAB_MESSAGES (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE COLLAB_MESSAGES (
    MESSAGE_ID           VARCHAR2(64)   PRIMARY KEY,
    GROUP_ID             VARCHAR2(64)   NOT NULL,
    SENDER_AGENT_ID      VARCHAR2(64)   NOT NULL,
    RECEIVER_AGENT_ID    VARCHAR2(64),
    PARENT_MESSAGE_ID    VARCHAR2(64),
    THREAD_ID            VARCHAR2(64),
    SUBJECT              VARCHAR2(500),
    BODY                 CLOB           NOT NULL,
    MESSAGE_TYPE         VARCHAR2(32)   DEFAULT 'TEXT' NOT NULL,
    PRIORITY             VARCHAR2(16)   DEFAULT 'NORMAL' NOT NULL,
    STATUS               VARCHAR2(16)   DEFAULT 'SENT' NOT NULL,
    ATTACHMENT_ENTITY_ID VARCHAR2(64),
    READ_AT              TIMESTAMP,
    CREATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CM_GROUP FOREIGN KEY (GROUP_ID) REFERENCES COLLAB_GROUPS(GROUP_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CM_SENDER FOREIGN KEY (SENDER_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_CM_RECEIVER FOREIGN KEY (RECEIVER_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_CM_PARENT FOREIGN KEY (PARENT_MESSAGE_ID) REFERENCES COLLAB_MESSAGES(MESSAGE_ID) ON DELETE SET NULL,
    CONSTRAINT FK_CM_THREAD FOREIGN KEY (THREAD_ID) REFERENCES COLLAB_MESSAGES(MESSAGE_ID) ON DELETE SET NULL,
    CONSTRAINT FK_CM_ATTACHMENT FOREIGN KEY (ATTACHMENT_ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT CK_CM_TYPE CHECK (MESSAGE_TYPE IN ('TEXT','QUERY','RESPONSE','ALERT','NOTIFICATION','COMMAND','REPORT')),
    CONSTRAINT CK_CM_PRIORITY CHECK (PRIORITY IN ('LOW','NORMAL','HIGH','URGENT')),
    CONSTRAINT CK_CM_STATUS CHECK (STATUS IN ('SENT','DELIVERED','READ','DELETED'))
);
CREATE INDEX IDX_CM_GROUP ON COLLAB_MESSAGES(GROUP_ID, CREATED_AT DESC);
CREATE INDEX IDX_CM_RECEIVER ON COLLAB_MESSAGES(RECEIVER_AGENT_ID, STATUS, CREATED_AT DESC);
CREATE INDEX IDX_CM_SENDER ON COLLAB_MESSAGES(SENDER_AGENT_ID, CREATED_AT DESC);
CREATE INDEX IDX_CM_THREAD ON COLLAB_MESSAGES(THREAD_ID, CREATED_AT);

PROMPT ============================================================
PROMPT 36. STEP_RETRY_POLICY (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE STEP_RETRY_POLICY (
    POLICY_ID          VARCHAR2(64)  PRIMARY KEY,
    STEP_ID           VARCHAR2(64)  NOT NULL,
    MAX_RETRIES        NUMBER(3,0)   DEFAULT 3,
    BACKOFF_SECONDS    NUMBER(5,0)   DEFAULT 5,
    BACKOFF_MULTIPLIER NUMBER(3,1)   DEFAULT 2.0,
    TIMEOUT_SECONDS    NUMBER(8,0),
    FALLBACK_ACTION    VARCHAR2(32)  DEFAULT 'FAIL',
    RETRY_COUNT        NUMBER(3,0)   DEFAULT 0,
    LAST_RETRY_AT      TIMESTAMP,
    CREATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SRP_STEP FOREIGN KEY (STEP_ID) REFERENCES TASK_STEPS(STEP_ID) ON DELETE CASCADE,
    CONSTRAINT CK_SRP_FALLBACK CHECK (FALLBACK_ACTION IN ('FAIL','SKIP','USE_CACHED','NOTIFY_COORDINATOR'))
);
CREATE INDEX IDX_SRP_STEP ON STEP_RETRY_POLICY(STEP_ID);

PROMPT ============================================================
PROMPT 37. STEP_EXECUTION_PLAN (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE STEP_EXECUTION_PLAN (
    PLAN_ID            VARCHAR2(64)  PRIMARY KEY,
    ROOT_PLAN_ID       VARCHAR2(64)  NOT NULL,
    STEP_GROUP_ID      NUMBER(5,0),
    STEP_ORDER         NUMBER(5,0)   NOT NULL,
    STEP_ID            VARCHAR2(64)  NOT NULL,
    PARENT_STEP_ID     VARCHAR2(64),
    PARALLEL_GROUP     NUMBER(5,0),
    STATUS             VARCHAR2(16)  DEFAULT 'PENDING',
    ASSIGNED_AGENT_ID  VARCHAR2(64),
    STARTED_AT         TIMESTAMP,
    COMPLETED_AT       TIMESTAMP,
    CONSTRAINT FK_SEP_PLAN FOREIGN KEY (ROOT_PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID),
    CONSTRAINT FK_SEP_STEP FOREIGN KEY (STEP_ID) REFERENCES TASK_STEPS(STEP_ID),
    CONSTRAINT FK_SEP_AGENT FOREIGN KEY (ASSIGNED_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT CK_SEP_STATUS CHECK (STATUS IN ('PENDING','RUNNING','COMPLETED','FAILED','SKIPPED','BLOCKED'))
);
CREATE INDEX IDX_SEP_PLAN ON STEP_EXECUTION_PLAN(ROOT_PLAN_ID, STEP_ORDER);
CREATE INDEX IDX_SEP_STATUS ON STEP_EXECUTION_PLAN(STATUS);

PROMPT ============================================================
PROMPT 38. EVENT_LOG (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE EVENT_LOG (
    EVENT_ID     VARCHAR2(64)  PRIMARY KEY,
    EVENT_TYPE   VARCHAR2(64)  NOT NULL,
    SOURCE_ID    VARCHAR2(64),
    SOURCE_TYPE  VARCHAR2(32),
    PAYLOAD      JSON,
    CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_EL_TYPE ON EVENT_LOG(EVENT_TYPE, CREATED_AT DESC);
CREATE INDEX IDX_EL_SOURCE ON EVENT_LOG(SOURCE_ID, EVENT_TYPE);

PROMPT ============================================================
PROMPT 39. EVENT_SUBSCRIPTIONS (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE EVENT_SUBSCRIPTIONS (
    SUB_ID         VARCHAR2(64)  PRIMARY KEY,
    AGENT_ID       VARCHAR2(64)  NOT NULL,
    EVENT_TYPE     VARCHAR2(64)  NOT NULL,
    FILTER_PATTERN VARCHAR2(500),
    ENABLED        VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ES_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT CK_ES_ENABLED CHECK (ENABLED IN ('Y','N')),
    CONSTRAINT UK_ES_AGENT_EVENT UNIQUE (AGENT_ID, EVENT_TYPE)
);
CREATE INDEX IDX_ES_EVENT ON EVENT_SUBSCRIPTIONS(EVENT_TYPE, ENABLED);

PROMPT ============================================================
PROMPT 40. AGENT_CAPABILITY_INDEX (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE AGENT_CAPABILITY_INDEX (
    CAP_ID        VARCHAR2(64)  PRIMARY KEY,
    AGENT_ID      VARCHAR2(64)  NOT NULL,
    CAPABILITY    VARCHAR2(256) NOT NULL,
    CONFIDENCE    NUMBER(5,4)   DEFAULT 1.0000,
    LAST_VERIFIED_AT TIMESTAMP,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ACI_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID)
);
CREATE INDEX IDX_ACI_CAP ON AGENT_CAPABILITY_INDEX(CAPABILITY);
CREATE INDEX IDX_ACI_AGENT ON AGENT_CAPABILITY_INDEX(AGENT_ID);

PROMPT ============================================================
PROMPT 41. TOOL_REGISTRY (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE TOOL_REGISTRY (
    TOOL_ID          VARCHAR2(64)  PRIMARY KEY,
    TOOL_NAME        VARCHAR2(256) NOT NULL,
    TOOL_NAMESPACE   VARCHAR2(64)  NOT NULL,
    TOOL_VERSION     VARCHAR2(32),
    DESCRIPTION      VARCHAR2(2000),
    INPUT_SCHEMA     JSON,
    OUTPUT_SCHEMA    JSON,
    RUNTIME_REQS     JSON,
    TOOL_TYPE        VARCHAR2(32)  DEFAULT 'API',
    STATUS           VARCHAR2(16)  DEFAULT 'ACTIVE',
    CALL_COUNT       NUMBER(10,0)  DEFAULT 0,
    LAST_CALLED_AT   TIMESTAMP,
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_TR_NAME UNIQUE (TOOL_NAME, TOOL_VERSION),
    CONSTRAINT CK_TR_TYPE CHECK (TOOL_TYPE IN ('API','FUNCTION','SQL','SCRIPT','WEBHOOK')),
    CONSTRAINT CK_TR_STATUS CHECK (STATUS IN ('ACTIVE','DEPRECATED','RETIRED'))
);
CREATE INDEX IDX_TR_NS ON TOOL_REGISTRY(TOOL_NAMESPACE);
CREATE INDEX IDX_TR_TYPE ON TOOL_REGISTRY(TOOL_TYPE);
CREATE INDEX IDX_TR_STATUS ON TOOL_REGISTRY(STATUS);

PROMPT ============================================================
PROMPT 42. TOOL_CHAINS (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE TOOL_CHAINS (
    CHAIN_ID         VARCHAR2(64)  PRIMARY KEY,
    CHAIN_NAME       VARCHAR2(256) NOT NULL,
    DESCRIPTION      VARCHAR2(2000),
    CREATED_BY       VARCHAR2(64),
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

PROMPT ============================================================
PROMPT 43. TOOL_CHAIN_STEPS (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE TOOL_CHAIN_STEPS (
    CHAIN_STEP_ID    VARCHAR2(64)  PRIMARY KEY,
    CHAIN_ID         VARCHAR2(64)  NOT NULL,
    STEP_ORDER       NUMBER(5,0)   NOT NULL,
    TOOL_ID          VARCHAR2(64)  NOT NULL,
    INPUT_MAPPING    JSON,
    OUTPUT_MAPPING   JSON,
    PARALLEL_GROUP   NUMBER(5,0),
    TIMEOUT_SECONDS  NUMBER(8,0),
    CONSTRAINT FK_TCS_CHAIN FOREIGN KEY (CHAIN_ID) REFERENCES TOOL_CHAINS(CHAIN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TCS_TOOL FOREIGN KEY (TOOL_ID) REFERENCES TOOL_REGISTRY(TOOL_ID)
);
CREATE INDEX IDX_TCS_CHAIN ON TOOL_CHAIN_STEPS(CHAIN_ID, STEP_ORDER);

PROMPT ============================================================
PROMPT v3.9.0 Extensions: MCP, Human-in-the-Loop Approval, Model Routing
PROMPT ============================================================

-- Add approval columns to STEP_EXECUTION_PLAN
ALTER TABLE STEP_EXECUTION_PLAN ADD (REQUIRES_APPROVAL CHAR(1) DEFAULT 'N');
ALTER TABLE STEP_EXECUTION_PLAN ADD (APPROVED_BY VARCHAR2(64));
ALTER TABLE STEP_EXECUTION_PLAN ADD (APPROVED_AT TIMESTAMP);

-- Add approval column to LOOP_META
ALTER TABLE LOOP_META ADD (REQUIRE_APPROVAL CHAR(1) DEFAULT 'N');

-- Add approval column to TOOL_REGISTRY
ALTER TABLE TOOL_REGISTRY ADD (REQUIRES_APPROVAL CHAR(1) DEFAULT 'N');

-- Update CK_SEP_STATUS constraint to include PAUSED
ALTER TABLE STEP_EXECUTION_PLAN DROP CONSTRAINT CK_SEP_STATUS;
ALTER TABLE STEP_EXECUTION_PLAN ADD CONSTRAINT CK_SEP_STATUS CHECK (STATUS IN ('PENDING','RUNNING','COMPLETED','FAILED','SKIPPED','BLOCKED','PAUSED'));

-- 44. APPROVAL_REQUESTS [NEW v3.9.0] - unified approval queue for steps, loops, and tool calls
CREATE TABLE APPROVAL_REQUESTS (
    APPROVAL_ID      VARCHAR2(64)   PRIMARY KEY,
    ENTITY_TYPE      VARCHAR2(32)   NOT NULL,
    ENTITY_ID        VARCHAR2(64)   NOT NULL,
    REQUESTED_BY     VARCHAR2(64)   NOT NULL,
    APPROVAL_STATUS  VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    APPROVED_BY      VARCHAR2(64),
    APPROVED_AT      TIMESTAMP,
    REJECT_REASON    VARCHAR2(500),
    CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_APRV_STATUS CHECK (APPROVAL_STATUS IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT CK_APRV_ENTITY CHECK (ENTITY_TYPE IN ('STEP','LOOP','TOOL'))
);
CREATE INDEX IDX_AR_STATUS ON APPROVAL_REQUESTS(APPROVAL_STATUS, CREATED_AT DESC);
CREATE INDEX IDX_AR_ENTITY ON APPROVAL_REQUESTS(ENTITY_TYPE, ENTITY_ID);

PROMPT ============================================================
PROMPT Seed Data
PROMPT ============================================================

INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('schema_version', '3.10.1', 'Current schema version');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('default_visibility', 'PRIVATE', 'Default visibility for new entities');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('max_importance', '10', 'Maximum importance value');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('embedding_url', 'http://10.10.10.1:12345/v1/embeddings', 'Embedding API URL for in-database generation');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('embedding_model', 'text-embedding-bge-m3', 'Embedding model name');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('embedding_dim', '1024', 'Default embedding dimension');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('retrieval_decay', '0.95', 'Retrieval count decay factor');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('dormant_timeout_min', '30', 'Auto-hibernate timeout in minutes');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('credential_encryption_key', 'CHANGE_ME_IN_PRODUCTION', 'Key for credential value encryption');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('license_type', 'COMMUNITY', 'License type: COMMUNITY or ENTERPRISE');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('session_timeout_min', '60', 'Session timeout in minutes');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('branch_cleanup_days', '90', 'Days before abandoned branches are auto-cleaned');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('branch_max_context_depth', '50', 'Max context nodes returned per branch chain');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('admin.registration_token', 'NOT_INITIALIZED', 'Admin token for Agent registration (run generate_admin_token to initialize)');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('trust_success_delta', '0.1', 'Trust increase on task success');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('trust_failure_delta', '0.15', 'Trust decrease on task failure');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('trust_min_threshold', '0.3', 'Min trust for task delegation');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('trust_max_value', '1.0', 'Max trust value');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('trust_initial_coordinator', '0.5', 'Initial trust to group coordinator');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('trust_initial_member', '0.3', 'Initial trust to other group members');

-- v3.10.0: EDGE_TYPE index for multi-type graph queries
CREATE INDEX IDX_EDGES_EDGE_TYPE ON ENTITY_EDGES(EDGE_TYPE) LOCAL;


INSERT INTO SYSTEM_USERS (USER_ID, USERNAME, PASSWORD_HASH, ROLE, STATUS, AUTH_SOURCE) VALUES ('admin', 'admin', 'SHA256:placeholder_change_me', 'ADMIN', 'ACTIVE', 'LOCAL');

COMMIT;

PROMPT ============================================================
PROMPT Oracle Text CONTEXT index for full-text search [NEW v2.3.2]
PROMPT ============================================================

BEGIN
    CTX_DDL.DROP_PREFERENCE('ENTITIES_MCD');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    CTX_DDL.CREATE_PREFERENCE('ENTITIES_MCD', 'MULTI_COLUMN_DATASTORE');
    CTX_DDL.SET_ATTRIBUTE('ENTITIES_MCD', 'COLUMNS', 'TITLE, CONTENT');
END;
/

CREATE INDEX ENTITIES_SEARCH_CTX ON ENTITIES(TITLE)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS ('DATASTORE ENTITIES_MCD SYNC (ON COMMIT)');

PROMPT ============================================================
PROMPT Drop helper procedures
PROMPT ============================================================

DROP PROCEDURE IF EXISTS safe_ddl;
DROP PROCEDURE IF EXISTS safe_idx;

PROMPT ============================================================
PROMPT AI Agent Infra v3.10.1 - Community Edition Schema Deployment Complete
PROMPT ============================================================

-- Grant DBMS_CRYPTO for DB_CRYPTO package
-- GRANT EXECUTE ON SYS.DBMS_CRYPTO TO AIADMIN;
