PROMPT ============================================================
PROMPT Oracle Memory System v2.1.0 - Schema Deployment
PROMPT Partitioned Tables with Composite Primary Keys
PROMPT ============================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE OR REPLACE PROCEDURE safe_ddl(p_sql IN VARCHAR2) IS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SAFE_DDL skipped: ' || p_sql || ' - ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE safe_idx(p_sql IN VARCHAR2) IS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            DBMS_OUTPUT.PUT_LINE('SAFE_IDX error: ' || p_sql || ' - ' || SQLERRM);
        END IF;
END;
/

PROMPT Dropping old property graph...
EXEC safe_ddl('DROP PROPERTY GRAPH IF EXISTS ORACLE_MEMORY_GRAPH');

PROMPT Dropping old duality views...
EXEC safe_ddl('DROP VIEW IF EXISTS MEMORY_DV');
EXEC safe_ddl('DROP VIEW IF EXISTS KNOWLEDGE_DV');

PROMPT Dropping all tables...
BEGIN
    FOR r IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE "' || r.table_name || '" CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

PROMPT ============================================================
PROMPT 1. ENTITIES (Partitioned by LIST + RANGE)
PROMPT ============================================================

CREATE TABLE ENTITIES (
    ENTITY_ID       VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE     VARCHAR2(32)  NOT NULL,
    TITLE           VARCHAR2(512) NOT NULL,
    CONTENT         CLOB,
    SUMMARY         VARCHAR2(2000),
    CATEGORY        VARCHAR2(64),
    STATUS          VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    OWNED_BY_AGENT  VARCHAR2(64),
    SOURCE_AGENT    VARCHAR2(64),
    VISIBILITY      VARCHAR2(16)  DEFAULT 'PRIVATE' NOT NULL,
    IMPORTANCE      NUMBER(3,0)   DEFAULT 5 NOT NULL,
    RETRIEVAL_COUNT NUMBER(10,0)  DEFAULT 0 NOT NULL,
    EXPIRES_AT      TIMESTAMP,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITIES PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_ENTITIES_STATUS CHECK (STATUS IN ('ACTIVE','ARCHIVED','DELETED','DRAFT')),
    CONSTRAINT CK_ENTITIES_VISIBILITY CHECK (VISIBILITY IN ('PRIVATE','SHARED','PUBLIC')),
    CONSTRAINT CK_ENTITIES_IMPORTANCE CHECK (IMPORTANCE BETWEEN 1 AND 10),
    CONSTRAINT CK_ENTITIES_TYPE CHECK (ENTITY_TYPE IN ('MEMORY','KNOWLEDGE','TASK_OUTPUT','EXPERIENCE','HARNESS_TEMPLATE','OTHER'))
) PARTITION BY LIST (ENTITY_TYPE)
SUBPARTITION BY RANGE (CREATED_AT)
SUBPARTITION TEMPLATE (
    SUBPARTITION SP_2026Q1 VALUES LESS THAN (TO_DATE('2026-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q2 VALUES LESS THAN (TO_DATE('2026-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q3 VALUES LESS THAN (TO_DATE('2026-10-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q4 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q1 VALUES LESS THAN (TO_DATE('2027-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q2 VALUES LESS THAN (TO_DATE('2027-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_FUTURE VALUES LESS THAN (MAXVALUE)
)
(
    PARTITION P_MEMORY        VALUES ('MEMORY'),
    PARTITION P_KNOWLEDGE     VALUES ('KNOWLEDGE'),
    PARTITION P_TASK_OUTPUT   VALUES ('TASK_OUTPUT'),
    PARTITION P_EXPERIENCE    VALUES ('EXPERIENCE'),
    PARTITION P_HARNESS       VALUES ('HARNESS_TEMPLATE'),
    PARTITION P_OTHERS        VALUES (DEFAULT)
);

ALTER TABLE ENTITIES ADD CONSTRAINT UK_ENTITIES_ID UNIQUE (ENTITY_ID);

PROMPT ============================================================
PROMPT 2. ENTITY_EDGES (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE ENTITY_EDGES (
    EDGE_ID       VARCHAR2(64)  NOT NULL,
    SOURCE_ID     VARCHAR2(64)  NOT NULL,
    SOURCE_TYPE   VARCHAR2(32)  NOT NULL,
    TARGET_ID     VARCHAR2(64)  NOT NULL,
    EDGE_TYPE     VARCHAR2(64)  NOT NULL,
    STRENGTH      NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    CONFIDENCE    NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    METADATA      JSON,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITY_EDGES PRIMARY KEY (EDGE_ID, SOURCE_ID),
    CONSTRAINT FK_EDGE_SOURCE FOREIGN KEY (SOURCE_ID, SOURCE_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_EDGE_STRENGTH CHECK (STRENGTH BETWEEN 0 AND 1),
    CONSTRAINT CK_EDGE_CONFIDENCE CHECK (CONFIDENCE BETWEEN 0 AND 1)
) PARTITION BY REFERENCE (FK_EDGE_SOURCE);

ALTER TABLE ENTITY_EDGES ADD CONSTRAINT UK_EDGES_ID UNIQUE (EDGE_ID);

PROMPT ============================================================
PROMPT 3. KNOWLEDGE_META (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE KNOWLEDGE_META (
    ENTITY_ID       VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE     VARCHAR2(32)  DEFAULT 'KNOWLEDGE' NOT NULL,
    DOMAIN          VARCHAR2(128),
    TOPIC           VARCHAR2(256),
    DIFFICULTY      VARCHAR2(16)  DEFAULT 'INTERMEDIATE' NOT NULL,
    REVIEW_COUNT    NUMBER(10,0)  DEFAULT 0 NOT NULL,
    LAST_REVIEWED   TIMESTAMP,
    NEXT_REVIEW     TIMESTAMP,
    CONSTRAINT PK_KNOWLEDGE_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_KM_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_KM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'KNOWLEDGE'),
    CONSTRAINT CK_KM_DIFFICULTY CHECK (DIFFICULTY IN ('BEGINNER','INTERMEDIATE','ADVANCED','EXPERT'))
) PARTITION BY REFERENCE (FK_KM_ENTITY);

PROMPT ============================================================
PROMPT 4. ENTITY_EMBEDDINGS (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE ENTITY_EMBEDDINGS (
    ENTITY_ID       VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE     VARCHAR2(32)  NOT NULL,
    EMBEDDING       VECTOR NOT NULL,
    EMBEDDING_MODEL VARCHAR2(128),
    EMBEDDING_DIM   NUMBER(5,0)   NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITY_EMBEDDINGS PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_EE_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE)
) PARTITION BY REFERENCE (FK_EE_ENTITY);

PROMPT ============================================================
PROMPT 5. HARNESS_META (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE HARNESS_META (
    ENTITY_ID         VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE       VARCHAR2(32)  DEFAULT 'HARNESS_TEMPLATE' NOT NULL,
    TEMPLATE_VERSION  VARCHAR2(32)  NOT NULL,
    INPUT_SCHEMA      JSON,
    OUTPUT_SCHEMA     JSON,
    EXECUTION_MODE    VARCHAR2(32)  DEFAULT 'SEQUENTIAL' NOT NULL,
    CONSTRAINT PK_HARNESS_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_HM_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_HM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'HARNESS_TEMPLATE'),
    CONSTRAINT CK_HM_EXEC_MODE CHECK (EXECUTION_MODE IN ('SEQUENTIAL','PARALLEL','CONDITIONAL'))
) PARTITION BY REFERENCE (FK_HM_ENTITY);

PROMPT ============================================================
PROMPT 6. TAGS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TAGS (
    TAG_ID    NUMBER(10,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TAG_NAME  VARCHAR2(128) NOT NULL,
    TAG_GROUP VARCHAR2(64),
    CONSTRAINT UK_TAGS_NAME UNIQUE (TAG_NAME)
);

PROMPT ============================================================
PROMPT 7. ENTITY_TAGS (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE ENTITY_TAGS (
    ENTITY_ID   VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE VARCHAR2(32)  NOT NULL,
    TAG_ID      NUMBER(10,0)  NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITY_TAGS PRIMARY KEY (ENTITY_ID, ENTITY_TYPE, TAG_ID),
    CONSTRAINT FK_ET_ENTITY FOREIGN KEY (ENTITY_ID, ENTITY_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT FK_ET_TAG FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID)
) PARTITION BY REFERENCE (FK_ET_ENTITY);

PROMPT ============================================================
PROMPT 8. AGENT_REGISTRY (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE AGENT_REGISTRY (
    AGENT_ID       VARCHAR2(64)  PRIMARY KEY,
    AGENT_NAME     VARCHAR2(256) NOT NULL,
    AGENT_TYPE     VARCHAR2(64),
    DESCRIPTION    VARCHAR2(2000),
    CAPABILITIES   JSON,
    CONFIG         JSON,
    WM_ENTITY_ID   VARCHAR2(64),
    STATUS         VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    LAST_SEEN_AT   TIMESTAMP,
    CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_AR_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','SUSPENDED','DECOMMISSIONED')),
    CONSTRAINT FK_AR_WM_ENTITY FOREIGN KEY (WM_ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID)
);
PROMPT ============================================================
PROMPT 9. AGENT_SESSION (Partitioned by LIST + RANGE)
PROMPT ============================================================

CREATE TABLE AGENT_SESSION (
    SESSION_ID    VARCHAR2(64)  NOT NULL,
    AGENT_ID      VARCHAR2(64)  NOT NULL,
    WM_ENTITY_ID  VARCHAR2(64),
    IS_ACTIVE     VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    START_TIME    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    END_TIME      TIMESTAMP,
    CONTEXT       JSON,
    CONSTRAINT PK_AGENT_SESSION PRIMARY KEY (SESSION_ID, IS_ACTIVE),
    CONSTRAINT CK_AS_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT FK_SESSION_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_SESSION_WM FOREIGN KEY (WM_ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID)
) PARTITION BY LIST (IS_ACTIVE)
SUBPARTITION BY RANGE (START_TIME)
SUBPARTITION TEMPLATE (
    SUBPARTITION SP_2026Q1 VALUES LESS THAN (TO_DATE('2026-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q2 VALUES LESS THAN (TO_DATE('2026-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q3 VALUES LESS THAN (TO_DATE('2026-10-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q4 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q1 VALUES LESS THAN (TO_DATE('2027-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q2 VALUES LESS THAN (TO_DATE('2027-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_FUTURE VALUES LESS THAN (MAXVALUE)
)
(
    PARTITION P_ACTIVE    VALUES ('Y'),
    PARTITION P_INACTIVE  VALUES ('N'),
    PARTITION P_OTHER     VALUES (DEFAULT)
);

ALTER TABLE AGENT_SESSION ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 10. ENTITY_ACCESS_LOG (Partitioned by RANGE + HASH)
PROMPT ============================================================

CREATE TABLE ENTITY_ACCESS_LOG (
    LOG_ID        VARCHAR2(64)  NOT NULL,
    ENTITY_ID     VARCHAR2(64)  NOT NULL,
    AGENT_ID      VARCHAR2(64)  NOT NULL,
    ACCESS_TYPE   VARCHAR2(32)  NOT NULL,
    ACCESS_TIME   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    SESSION_ID    VARCHAR2(64),
    CONTEXT       JSON,
    CONSTRAINT CK_EAL_ACCESS_TYPE CHECK (ACCESS_TYPE IN ('READ','WRITE','DELETE','SEARCH','EMBED'))
) PARTITION BY RANGE (ACCESS_TIME)
SUBPARTITION BY HASH (AGENT_ID) SUBPARTITIONS 4
(
    PARTITION P_202605 VALUES LESS THAN (TO_DATE('2026-06-01','YYYY-MM-DD')),
    PARTITION P_202606 VALUES LESS THAN (TO_DATE('2026-07-01','YYYY-MM-DD')),
    PARTITION P_MAX    VALUES LESS THAN (MAXVALUE)
);

ALTER TABLE ENTITY_ACCESS_LOG ADD CONSTRAINT UK_ACCESS_LOG_ID UNIQUE (LOG_ID);

ALTER TABLE ENTITY_ACCESS_LOG ADD CONSTRAINT FK_EAL_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID);
ALTER TABLE ENTITY_ACCESS_LOG ADD CONSTRAINT FK_EAL_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID);

PROMPT ============================================================
PROMPT 11. AGENT_PERMISSION_LOG (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE AGENT_PERMISSION_LOG (
    LOG_ID        VARCHAR2(64)  PRIMARY KEY,
    AGENT_ID      VARCHAR2(64)  NOT NULL,
    GRANTED_BY    VARCHAR2(64),
    PERMISSION    VARCHAR2(128) NOT NULL,
    RESOURCE_TYPE VARCHAR2(64)  NOT NULL,
    RESOURCE_ID   VARCHAR2(64)  NOT NULL,
    ACTION        VARCHAR2(32)  NOT NULL,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_APL_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT CK_APL_ACTION CHECK (ACTION IN ('GRANT','REVOKE','DENY'))
);

PROMPT ============================================================
PROMPT 12. AGENT_COLLABORATION (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE AGENT_COLLABORATION (
    COL_ID          VARCHAR2(64)  PRIMARY KEY,
    SOURCE_AGENT_ID VARCHAR2(64)  NOT NULL,
    TARGET_AGENT_ID VARCHAR2(64)  NOT NULL,
    COL_TYPE        VARCHAR2(64)  NOT NULL,
    ENTITY_ID       VARCHAR2(64),
    CONTEXT         JSON,
    STRENGTH        NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_COL_SOURCE FOREIGN KEY (SOURCE_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_COL_TARGET FOREIGN KEY (TARGET_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID),
    CONSTRAINT FK_COL_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT CK_COL_STRENGTH CHECK (STRENGTH BETWEEN 0 AND 1)
);

PROMPT ============================================================
PROMPT 13. TASK_PLANS (Partitioned by LIST + RANGE)
PROMPT ============================================================

CREATE TABLE TASK_PLANS (
    PLAN_ID        VARCHAR2(64)   NOT NULL,
    AGENT_ID       VARCHAR2(64)   NOT NULL,
    GOAL           VARCHAR2(2000) NOT NULL,
    STATUS         VARCHAR2(30)   DEFAULT 'PENDING' NOT NULL,
    PRIORITY       NUMBER(3,0)    DEFAULT 5 NOT NULL,
    STRATEGY       VARCHAR2(64),
    RESULT_SUMMARY VARCHAR2(2000),
    CREATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT   TIMESTAMP,
    CONSTRAINT PK_TASK_PLANS PRIMARY KEY (PLAN_ID, STATUS),
    CONSTRAINT CK_TP_STATUS CHECK (STATUS IN ('PENDING','RUNNING','BLOCKED','SUCCESS','FAILED','CANCELLED')),
    CONSTRAINT CK_TP_PRIORITY CHECK (PRIORITY BETWEEN 1 AND 10),
    CONSTRAINT FK_TP_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID)
) PARTITION BY LIST (STATUS)
SUBPARTITION BY RANGE (CREATED_AT)
SUBPARTITION TEMPLATE (
    SUBPARTITION SP_2026Q1 VALUES LESS THAN (TO_DATE('2026-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q2 VALUES LESS THAN (TO_DATE('2026-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q3 VALUES LESS THAN (TO_DATE('2026-10-01','YYYY-MM-DD')),
    SUBPARTITION SP_2026Q4 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q1 VALUES LESS THAN (TO_DATE('2027-04-01','YYYY-MM-DD')),
    SUBPARTITION SP_2027Q2 VALUES LESS THAN (TO_DATE('2027-07-01','YYYY-MM-DD')),
    SUBPARTITION SP_FUTURE VALUES LESS THAN (MAXVALUE)
)
(
    PARTITION P_ACTIVE    VALUES ('PENDING','RUNNING','BLOCKED'),
    PARTITION P_TERMINAL  VALUES ('SUCCESS','FAILED','CANCELLED'),
    PARTITION P_OTHER     VALUES (DEFAULT)
);

ALTER TABLE TASK_PLANS ADD CONSTRAINT UK_TASK_PLANS_ID UNIQUE (PLAN_ID);

ALTER TABLE TASK_STEPS ENABLE ROW MOVEMENT;
ALTER TABLE TASK_PLANS ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 14. TASK_STEPS (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_STEPS (
    STEP_ID       VARCHAR2(64)   NOT NULL,
    PLAN_ID       VARCHAR2(64)   NOT NULL,
    PLAN_STATUS   VARCHAR2(30)   NOT NULL,
    STEP_ORDER    NUMBER(5,0)    NOT NULL,
    DESCRIPTION   VARCHAR2(2000) NOT NULL,
    TOOL_NAME     VARCHAR2(128),
    TOOL_INPUT    JSON,
    TOOL_OUTPUT   JSON,
    STATUS        VARCHAR2(30)   DEFAULT 'PENDING' NOT NULL,
    STARTED_AT    TIMESTAMP,
    COMPLETED_AT  TIMESTAMP,
    CONSTRAINT PK_TASK_STEPS PRIMARY KEY (STEP_ID, PLAN_ID),
    CONSTRAINT FK_STEP_PLAN FOREIGN KEY (PLAN_ID, PLAN_STATUS) REFERENCES TASK_PLANS(PLAN_ID, STATUS),
    CONSTRAINT CK_TS_STATUS CHECK (STATUS IN ('PENDING','RUNNING','BLOCKED','SUCCESS','FAILED','SKIPPED'))
) PARTITION BY REFERENCE (FK_STEP_PLAN);

ALTER TABLE TASK_STEPS ADD CONSTRAINT UK_TASK_STEPS_ID UNIQUE (STEP_ID);

PROMPT ============================================================
PROMPT 15. TASK_CONTEXT_SNAPSHOTS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_CONTEXT_SNAPSHOTS (
    SNAPSHOT_ID   VARCHAR2(64)  PRIMARY KEY,
    PLAN_ID       VARCHAR2(64)  NOT NULL,
    SNAPSHOT_TYPE VARCHAR2(64)  NOT NULL,
    CONTEXT_DATA  JSON,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SNAP_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID)
);

PROMPT ============================================================
PROMPT 16. TASK_TOOL_CALLS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_TOOL_CALLS (
    CALL_ID      VARCHAR2(64)  PRIMARY KEY,
    PLAN_ID      VARCHAR2(64)  NOT NULL,
    STEP_ID      VARCHAR2(64),
    TOOL_NAME    VARCHAR2(128) NOT NULL,
    TOOL_INPUT   JSON,
    TOOL_OUTPUT  JSON,
    STATUS       VARCHAR2(30)  DEFAULT 'PENDING' NOT NULL,
    DURATION_MS  NUMBER(10,0),
    CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_TC_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID),
    CONSTRAINT FK_TC_STEP FOREIGN KEY (STEP_ID) REFERENCES TASK_STEPS(STEP_ID),
    CONSTRAINT CK_TTC_STATUS CHECK (STATUS IN ('PENDING','RUNNING','SUCCESS','FAILED','TIMEOUT'))
);

PROMPT ============================================================
PROMPT 17. TASK_DEPENDENCIES (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_DEPENDENCIES (
    DEP_ID          VARCHAR2(64)  PRIMARY KEY,
    SOURCE_PLAN_ID  VARCHAR2(64)  NOT NULL,
    TARGET_PLAN_ID  VARCHAR2(64)  NOT NULL,
    DEP_TYPE        VARCHAR2(64)  NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DEP_SOURCE FOREIGN KEY (SOURCE_PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID),
    CONSTRAINT FK_DEP_TARGET FOREIGN KEY (TARGET_PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID),
    CONSTRAINT CK_DEP_TYPE CHECK (DEP_TYPE IN ('BLOCKS','DEPENDS_ON','TRIGGERS','RELATES_TO'))
);

PROMPT ============================================================
PROMPT 18. SYSTEM_CONFIG (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE SYSTEM_CONFIG (
    CONFIG_KEY   VARCHAR2(128) PRIMARY KEY,
    CONFIG_VALUE VARCHAR2(4000) NOT NULL,
    DESCRIPTION  VARCHAR2(2000),
    UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

PROMPT ============================================================
PROMPT 19. SYSTEM_USERS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE SYSTEM_USERS (
    USER_ID     VARCHAR2(64)  PRIMARY KEY,
    USERNAME    VARCHAR2(128) NOT NULL,
    PASSWORD_HASH VARCHAR2(256),
    ROLE        VARCHAR2(64)  DEFAULT 'USER' NOT NULL,
    STATUS      VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    LAST_LOGIN  TIMESTAMP,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_SU_ROLE CHECK (ROLE IN ('ADMIN','USER','SERVICE')),
    CONSTRAINT CK_SU_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','LOCKED'))
);

PROMPT ============================================================
PROMPT Local Indexes on ENTITIES
PROMPT ============================================================

CREATE INDEX IDX_ENTITIES_CATEGORY ON ENTITIES(CATEGORY) LOCAL;
CREATE INDEX IDX_ENTITIES_STATUS ON ENTITIES(STATUS) LOCAL;
CREATE INDEX IDX_ENTITIES_OWNED_BY ON ENTITIES(OWNED_BY_AGENT) LOCAL;
CREATE INDEX IDX_ENTITIES_VISIBILITY ON ENTITIES(VISIBILITY) LOCAL;

PROMPT ============================================================
PROMPT Local Indexes on ENTITY_EDGES
PROMPT ============================================================

CREATE INDEX IDX_EDGES_TARGET ON ENTITY_EDGES(TARGET_ID) LOCAL;
CREATE INDEX IDX_EDGES_TYPE ON ENTITY_EDGES(EDGE_TYPE) LOCAL;
CREATE INDEX IDX_EDGES_TARGET_TYPE ON ENTITY_EDGES(TARGET_ID, EDGE_TYPE) LOCAL;

PROMPT ============================================================
PROMPT Other Indexes
PROMPT ============================================================

CREATE INDEX IDX_KM_DOMAIN ON KNOWLEDGE_META(DOMAIN) LOCAL;
CREATE INDEX IDX_KM_TOPIC ON KNOWLEDGE_META(TOPIC) LOCAL;
CREATE INDEX IDX_KM_NEXT_REVIEW ON KNOWLEDGE_META(NEXT_REVIEW) LOCAL;

CREATE INDEX IDX_EE_MODEL ON ENTITY_EMBEDDINGS(EMBEDDING_MODEL) LOCAL;

CREATE INDEX IDX_ET_TAG ON ENTITY_TAGS(TAG_ID) LOCAL;

CREATE INDEX IDX_AR_STATUS ON AGENT_REGISTRY(STATUS);
CREATE INDEX IDX_AR_TYPE ON AGENT_REGISTRY(AGENT_TYPE);

CREATE INDEX IDX_AS_AGENT ON AGENT_SESSION(AGENT_ID) LOCAL;

CREATE INDEX IDX_EAL_ENTITY ON ENTITY_ACCESS_LOG(ENTITY_ID) LOCAL;
CREATE INDEX IDX_EAL_TIME ON ENTITY_ACCESS_LOG(ACCESS_TIME) LOCAL;

CREATE INDEX IDX_APL_AGENT ON AGENT_PERMISSION_LOG(AGENT_ID);

CREATE INDEX IDX_COL_SOURCE ON AGENT_COLLABORATION(SOURCE_AGENT_ID);
CREATE INDEX IDX_COL_TARGET ON AGENT_COLLABORATION(TARGET_AGENT_ID);

CREATE INDEX IDX_TP_AGENT ON TASK_PLANS(AGENT_ID) LOCAL;
CREATE INDEX IDX_TS_PLAN ON TASK_STEPS(PLAN_ID) LOCAL;

CREATE INDEX IDX_TCS_PLAN ON TASK_CONTEXT_SNAPSHOTS(PLAN_ID);
CREATE INDEX IDX_TTC_PLAN ON TASK_TOOL_CALLS(PLAN_ID);
CREATE INDEX IDX_TTC_STEP ON TASK_TOOL_CALLS(STEP_ID);

CREATE INDEX IDX_TD_SOURCE ON TASK_DEPENDENCIES(SOURCE_PLAN_ID);
CREATE INDEX IDX_TD_TARGET ON TASK_DEPENDENCIES(TARGET_PLAN_ID);

PROMPT ============================================================
PROMPT Property Graph: ORACLE_MEMORY_GRAPH
PROMPT ============================================================

CREATE PROPERTY GRAPH ORACLE_MEMORY_GRAPH
  VERTEX TABLES (
    ENTITIES
      KEY (ENTITY_ID, ENTITY_TYPE)
      PROPERTIES (ENTITY_ID, ENTITY_TYPE, TITLE, CATEGORY, STATUS, OWNED_BY_AGENT, VISIBILITY, IMPORTANCE, CREATED_AT, UPDATED_AT)
  )
  EDGE TABLES (
    ENTITY_EDGES
      KEY (EDGE_ID, SOURCE_ID)
      SOURCE KEY (SOURCE_ID, SOURCE_TYPE) REFERENCES ENTITIES(ENTITY_ID, ENTITY_TYPE)
      DESTINATION KEY (TARGET_ID) REFERENCES ENTITIES(ENTITY_ID)
      PROPERTIES (EDGE_ID, EDGE_TYPE, STRENGTH, CONFIDENCE, CREATED_AT)
  );

PROMPT ============================================================
PROMPT JSON-Relational Duality View: MEMORY_DV
PROMPT ============================================================

CREATE JSON RELATIONAL DUALITY VIEW MEMORY_DV AS
SELECT JSON {
    '_id'          : JSON {'entity_id': e.ENTITY_ID, 'entity_type': e.ENTITY_TYPE},
    'title'        : e.TITLE,
    'content'      : e.CONTENT,
    'summary'      : e.SUMMARY,
    'category'     : e.CATEGORY,
    'status'       : e.STATUS,
    'owned_by'     : e.OWNED_BY_AGENT,
    'source_agent' : e.SOURCE_AGENT,
    'visibility'   : e.VISIBILITY,
    'importance'   : e.IMPORTANCE,
    'created_at'   : e.CREATED_AT,
    'updated_at'   : e.UPDATED_AT,
    'edges' : [
        SELECT JSON {
            'edge_id'   : eg.EDGE_ID,
            'edge_type' : eg.EDGE_TYPE,
            'target_id' : eg.TARGET_ID,
            'strength'  : eg.STRENGTH,
            'confidence': eg.CONFIDENCE
        }
        FROM ENTITY_EDGES eg
        WHERE eg.SOURCE_ID = e.ENTITY_ID AND eg.SOURCE_TYPE = e.ENTITY_TYPE
    ],
    'tags' : [
        SELECT JSON {
            'tag_id' : et.TAG_ID
        }
        FROM ENTITY_TAGS et
        WHERE et.ENTITY_ID = e.ENTITY_ID AND et.ENTITY_TYPE = e.ENTITY_TYPE
    ]
}
FROM ENTITIES e;

PROMPT ============================================================
PROMPT JSON-Relational Duality View: KNOWLEDGE_DV
PROMPT ============================================================

CREATE JSON RELATIONAL DUALITY VIEW KNOWLEDGE_DV AS
SELECT JSON {
    '_id'           : JSON {'entity_id': e.ENTITY_ID, 'entity_type': e.ENTITY_TYPE},
    'title'         : e.TITLE,
    'content'       : e.CONTENT,
    'summary'       : e.SUMMARY,
    'category'      : e.CATEGORY,
    'status'        : e.STATUS,
    'visibility'    : e.VISIBILITY,
    'importance'    : e.IMPORTANCE,
    'created_at'    : e.CREATED_AT,
    'updated_at'    : e.UPDATED_AT,
    'knowledge_meta' : [
        SELECT JSON {
            'domain'        : km.DOMAIN,
            'topic'         : km.TOPIC,
            'difficulty'    : km.DIFFICULTY,
            'review_count'  : km.REVIEW_COUNT,
            'last_reviewed' : km.LAST_REVIEWED,
            'next_review'   : km.NEXT_REVIEW
        }
        FROM KNOWLEDGE_META km
        WHERE km.ENTITY_ID = e.ENTITY_ID AND km.ENTITY_TYPE = e.ENTITY_TYPE
    ],
    'edges' : [
        SELECT JSON {
            'edge_id'   : eg.EDGE_ID,
            'edge_type' : eg.EDGE_TYPE,
            'target_id' : eg.TARGET_ID,
            'strength'  : eg.STRENGTH,
            'confidence': eg.CONFIDENCE
        }
        FROM ENTITY_EDGES eg
        WHERE eg.SOURCE_ID = e.ENTITY_ID AND eg.SOURCE_TYPE = e.ENTITY_TYPE
    ],
    'tags' : [
        SELECT JSON {
            'tag_id' : et.TAG_ID
        }
        FROM ENTITY_TAGS et
        WHERE et.ENTITY_ID = e.ENTITY_ID AND et.ENTITY_TYPE = e.ENTITY_TYPE
    ]
}
FROM ENTITIES e;

PROMPT ============================================================
PROMPT Seed Data
PROMPT ============================================================

INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('schema_version', '2.1.0', 'Current schema version');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('default_visibility', 'PRIVATE', 'Default visibility for new entities');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('max_importance', '10', 'Maximum importance value');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('embedding_dim', '1536', 'Default embedding dimension');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('retrieval_decay', '0.95', 'Retrieval count decay factor');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('session_timeout_min', '60', 'Session timeout in minutes');

INSERT INTO SYSTEM_USERS (USER_ID, USERNAME, PASSWORD_HASH, ROLE, STATUS) VALUES ('admin', 'admin', 'SHA256:placeholder_change_me', 'ADMIN', 'ACTIVE');

COMMIT;

PROMPT ============================================================
PROMPT Drop helper procedures
PROMPT ============================================================

DROP PROCEDURE IF EXISTS safe_ddl;
DROP PROCEDURE IF EXISTS safe_idx;

PROMPT ============================================================
PROMPT Oracle Memory System v2.1.0 Schema Deployment Complete
PROMPT ============================================================
