-- ============================================================
-- 4_grants.sql — Restricted Database User & Access Control
-- AI Agent Infra with OracleDB v3.7.0
-- ============================================================
-- 
-- This script creates a restricted database user (AGENT_API) that
-- Agents should use for runtime connections instead of the schema
-- owner (AIADMIN). The restricted user:
--   - Can EXECUTE PL/SQL API packages (AUTHID DEFINER)
--   - Can SELECT on tables (read-only access)
--   - CANNOT INSERT/UPDATE/DELETE directly on tables
--   - CANNOT CREATE/ALTER/DROP tables, views, or procedures
--   - CANNOT perform DDL of any kind
--
-- Prerequisites:
--   - Run as SYSDBA: sql sys/password@//host:port/service as sysdba @4_grants.sql
--   - Schema owner (AIADMIN) must already exist with all objects deployed
--
-- ============================================================

PROMPT ============================================================
PROMPT Creating restricted database user: AGENT_API
PROMPT ============================================================

-- Create user (adjust tablespace/quota as needed)
CREATE USER AGENT_API IDENTIFIED BY "agent_api_2026" DEFAULT TABLESPACE USERS QUOTA 0 ON USERS;
GRANT CREATE SESSION TO AGENT_API;

PROMPT ============================================================
PROMPT Granting EXECUTE on PL/SQL API packages
PROMPT ============================================================
-- These packages use AUTHID DEFINER (default), so they execute
-- with AIADMIN privileges while enforcing business logic.

GRANT EXECUTE ON AIADMIN.MEMORY_FUSION_ENGINE TO AGENT_API;
GRANT EXECUTE ON AIADMIN.KNOWLEDGE_BASE_API TO AGENT_API;
GRANT EXECUTE ON AIADMIN.AGENT_PERMISSION_MANAGER TO AGENT_API;
GRANT EXECUTE ON AIADMIN.SESSION_CLEANUP TO AGENT_API;
GRANT EXECUTE ON AIADMIN.WORKSPACE_MANAGER TO AGENT_API;
GRANT EXECUTE ON AIADMIN.SPEC_MANAGER TO AGENT_API;
GRANT EXECUTE ON AIADMIN.COLLAB_GROUP_MANAGER TO AGENT_API;
GRANT EXECUTE ON AIADMIN.EMBEDDING_MANAGER TO AGENT_API;
GRANT EXECUTE ON AIADMIN.DB_CRYPTO TO AGENT_API;
GRANT EXECUTE ON AIADMIN.BRANCH_MANAGER TO AGENT_API;

PROMPT ============================================================
PROMPT Granting SELECT on tables (read-only access)
PROMPT ============================================================
-- Agents can query data directly but cannot modify it.
-- All modifications must go through PL/SQL packages.

GRANT SELECT ON AIADMIN.ENTITIES TO AGENT_API;
GRANT SELECT ON AIADMIN.ENTITY_EDGES TO AGENT_API;
GRANT SELECT ON AIADMIN.KNOWLEDGE_META TO AGENT_API;
GRANT SELECT ON AIADMIN.ENTITY_EMBEDDINGS TO AGENT_API;
GRANT SELECT ON AIADMIN.HARNESS_META TO AGENT_API;
GRANT SELECT ON AIADMIN.CONTEXT_BRANCHES TO AGENT_API;
GRANT SELECT ON AIADMIN.SPEC_META TO AGENT_API;
GRANT SELECT ON AIADMIN.SKILL_META TO AGENT_API;
GRANT SELECT ON AIADMIN.TAGS TO AGENT_API;
GRANT SELECT ON AIADMIN.ENTITY_TAGS TO AGENT_API;
GRANT SELECT ON AIADMIN.SYSTEM_USERS TO AGENT_API;
GRANT SELECT ON AIADMIN.AGENT_REGISTRY TO AGENT_API;
GRANT SELECT ON AIADMIN.AGENT_CREDENTIALS TO AGENT_API;
GRANT SELECT ON AIADMIN.WORKSPACES TO AGENT_API;
GRANT SELECT ON AIADMIN.WORKSPACE_CONTEXT TO AGENT_API;
GRANT SELECT ON AIADMIN.BRANCH_MERGE_LOG TO AGENT_API;
GRANT SELECT ON AIADMIN.AGENT_SESSION TO AGENT_API;
GRANT SELECT ON AIADMIN.ENTITY_ACCESS_LOG TO AGENT_API;
GRANT SELECT ON AIADMIN.AGENT_PERMISSION_LOG TO AGENT_API;
GRANT SELECT ON AIADMIN.AGENT_COLLABORATION TO AGENT_API;
GRANT SELECT ON AIADMIN.COLLAB_GROUPS TO AGENT_API;
GRANT SELECT ON AIADMIN.COLLAB_GROUP_MEMBERS TO AGENT_API;
GRANT SELECT ON AIADMIN.TASK_PLANS TO AGENT_API;
GRANT SELECT ON AIADMIN.TASK_STEPS TO AGENT_API;
GRANT SELECT ON AIADMIN.TASK_CONTEXT_SNAPSHOTS TO AGENT_API;
GRANT SELECT ON AIADMIN.TASK_TOOL_CALLS TO AGENT_API;
GRANT SELECT ON AIADMIN.TASK_DEPENDENCIES TO AGENT_API;
GRANT SELECT ON AIADMIN.SPEC_PLAN_LINKS TO AGENT_API;
GRANT SELECT ON AIADMIN.WORKSPACE_TASKS TO AGENT_API;
-- SYSTEM_CONFIG: NOT granted — protected by Deep Sec Data Grant (admin_data_role only)
-- Agents must access config through PL/SQL packages (DB_CRYPTO)

PROMPT ============================================================
PROMPT Granting SELECT on views
PROMPT ============================================================

GRANT SELECT ON AIADMIN.BRANCH_COMPARISON TO AGENT_API;

PROMPT ============================================================
PROMPT Creating synonyms for convenience
PROMPT ============================================================
-- Allows AGENT_API to reference objects without AIADMIN. prefix

CREATE SYNONYM AGENT_API.MEMORY_FUSION_ENGINE FOR AIADMIN.MEMORY_FUSION_ENGINE;
CREATE SYNONYM AGENT_API.KNOWLEDGE_BASE_API FOR AIADMIN.KNOWLEDGE_BASE_API;
CREATE SYNONYM AGENT_API.AGENT_PERMISSION_MANAGER FOR AIADMIN.AGENT_PERMISSION_MANAGER;
CREATE SYNONYM AGENT_API.SESSION_CLEANUP FOR AIADMIN.SESSION_CLEANUP;
CREATE SYNONYM AGENT_API.WORKSPACE_MANAGER FOR AIADMIN.WORKSPACE_MANAGER;
CREATE SYNONYM AGENT_API.SPEC_MANAGER FOR AIADMIN.SPEC_MANAGER;
CREATE SYNONYM AGENT_API.COLLAB_GROUP_MANAGER FOR AIADMIN.COLLAB_GROUP_MANAGER;
CREATE SYNONYM AGENT_API.EMBEDDING_MANAGER FOR AIADMIN.EMBEDDING_MANAGER;
CREATE SYNONYM AGENT_API.DB_CRYPTO FOR AIADMIN.DB_CRYPTO;
CREATE SYNONYM AGENT_API.BRANCH_MANAGER FOR AIADMIN.BRANCH_MANAGER;

CREATE SYNONYM AGENT_API.ENTITIES FOR AIADMIN.ENTITIES;
CREATE SYNONYM AGENT_API.ENTITY_EDGES FOR AIADMIN.ENTITY_EDGES;
CREATE SYNONYM AGENT_API.KNOWLEDGE_META FOR AIADMIN.KNOWLEDGE_META;
CREATE SYNONYM AGENT_API.ENTITY_EMBEDDINGS FOR AIADMIN.ENTITY_EMBEDDINGS;
CREATE SYNONYM AGENT_API.HARNESS_META FOR AIADMIN.HARNESS_META;
CREATE SYNONYM AGENT_API.CONTEXT_BRANCHES FOR AIADMIN.CONTEXT_BRANCHES;
CREATE SYNONYM AGENT_API.SPEC_META FOR AIADMIN.SPEC_META;
CREATE SYNONYM AGENT_API.SKILL_META FOR AIADMIN.SKILL_META;
CREATE SYNONYM AGENT_API.TAGS FOR AIADMIN.TAGS;
CREATE SYNONYM AGENT_API.ENTITY_TAGS FOR AIADMIN.ENTITY_TAGS;
CREATE SYNONYM AGENT_API.SYSTEM_USERS FOR AIADMIN.SYSTEM_USERS;
CREATE SYNONYM AGENT_API.AGENT_REGISTRY FOR AIADMIN.AGENT_REGISTRY;
CREATE SYNONYM AGENT_API.AGENT_CREDENTIALS FOR AIADMIN.AGENT_CREDENTIALS;
CREATE SYNONYM AGENT_API.WORKSPACES FOR AIADMIN.WORKSPACES;
CREATE SYNONYM AGENT_API.WORKSPACE_CONTEXT FOR AIADMIN.WORKSPACE_CONTEXT;
CREATE SYNONYM AGENT_API.BRANCH_MERGE_LOG FOR AIADMIN.BRANCH_MERGE_LOG;
CREATE SYNONYM AGENT_API.AGENT_SESSION FOR AIADMIN.AGENT_SESSION;
CREATE SYNONYM AGENT_API.ENTITY_ACCESS_LOG FOR AIADMIN.ENTITY_ACCESS_LOG;
CREATE SYNONYM AGENT_API.AGENT_PERMISSION_LOG FOR AIADMIN.AGENT_PERMISSION_LOG;
CREATE SYNONYM AGENT_API.AGENT_COLLABORATION FOR AIADMIN.AGENT_COLLABORATION;
CREATE SYNONYM AGENT_API.COLLAB_GROUPS FOR AIADMIN.COLLAB_GROUPS;
CREATE SYNONYM AGENT_API.COLLAB_GROUP_MEMBERS FOR AIADMIN.COLLAB_GROUP_MEMBERS;
CREATE SYNONYM AGENT_API.TASK_PLANS FOR AIADMIN.TASK_PLANS;
CREATE SYNONYM AGENT_API.TASK_STEPS FOR AIADMIN.TASK_STEPS;
CREATE SYNONYM AGENT_API.TASK_CONTEXT_SNAPSHOTS FOR AIADMIN.TASK_CONTEXT_SNAPSHOTS;
CREATE SYNONYM AGENT_API.TASK_TOOL_CALLS FOR AIADMIN.TASK_TOOL_CALLS;
CREATE SYNONYM AGENT_API.TASK_DEPENDENCIES FOR AIADMIN.TASK_DEPENDENCIES;
CREATE SYNONYM AGENT_API.SPEC_PLAN_LINKS FOR AIADMIN.SPEC_PLAN_LINKS;
CREATE SYNONYM AGENT_API.WORKSPACE_TASKS FOR AIADMIN.WORKSPACE_TASKS;
-- SYSTEM_CONFIG synonym intentionally NOT created (protected by Deep Sec)

CREATE SYNONYM AGENT_API.BRANCH_COMPARISON FOR AIADMIN.BRANCH_COMPARISON;

PROMPT ============================================================
PROMPT Revoking dangerous privileges (safety net)
PROMPT ============================================================
-- AGENT_API should NEVER have these. These REVOKE statements
-- are a safety net in case they were accidentally granted.

REVOKE CREATE TABLE FROM AGENT_API;
REVOKE CREATE VIEW FROM AGENT_API;
REVOKE CREATE PROCEDURE FROM AGENT_API;
REVOKE CREATE TRIGGER FROM AGENT_API;
REVOKE CREATE SEQUENCE FROM AGENT_API;
REVOKE CREATE TYPE FROM AGENT_API;
REVOKE ALTER ANY TABLE FROM AGENT_API;
REVOKE DROP ANY TABLE FROM AGENT_API;
REVOKE INSERT ANY TABLE FROM AGENT_API;
REVOKE UPDATE ANY TABLE FROM AGENT_API;
REVOKE DELETE ANY TABLE FROM AGENT_API;

PROMPT ============================================================
PROMPT Granting Deep Data Security privileges to AIADMIN
PROMPT ============================================================

GRANT CREATE END USER TO AIADMIN;
GRANT CREATE END USER CONTEXT TO AIADMIN;
GRANT CREATE ANY END USER CONTEXT TO AIADMIN;
GRANT CREATE END USER SECURITY CONTEXT TO AIADMIN;
GRANT CREATE DATA GRANT TO AIADMIN;
GRANT CREATE ANY DATA GRANT TO AIADMIN;
GRANT ADMINISTER ANY DATA GRANT TO AIADMIN;
GRANT CREATE DATA ROLE TO AIADMIN;
GRANT DROP DATA ROLE TO AIADMIN;
GRANT GRANT ANY DATA ROLE TO AIADMIN;
GRANT SET USE DATA GRANTS ONLY TO AIADMIN;
GRANT ALTER END USER TO AIADMIN;
GRANT DROP END USER TO AIADMIN;
GRANT CREATE ANY CONTEXT TO AIADMIN;

PROMPT ============================================================
PROMPT Creating DEEP_SEC_SESSION_ROLE for End User login
PROMPT ============================================================
-- This role carries CREATE SESSION for Deep Sec End Users.
-- End Users connect via Direct Logon with this role granted
-- through their Data Role (agent_data_role / admin_data_role / pool_agent_data_role).

CREATE ROLE DEEP_SEC_SESSION_ROLE;
GRANT CREATE SESSION TO DEEP_SEC_SESSION_ROLE;
GRANT DEEP_SEC_SESSION_ROLE TO AIADMIN WITH ADMIN OPTION;

PROMPT ============================================================
PROMPT AGENT_API user setup complete
PROMPT ============================================================
PROMPT 
PROMPT Connection string for Agents:
PROMPT   user=AGENT_API, password=agent_api_2026, dsn=<same_as_aiadmin>
PROMPT 
PROMPT IMPORTANT: Update config.json to use AGENT_API credentials
PROMPT           for runtime Agent connections. Keep AIADMIN
PROMPT           credentials for deployment only.
PROMPT ============================================================
