-- v4.4.9: preserve explicit LOCAL authentication for Oracle-compatible runtimes.
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE SYSTEM_USERS DROP CONSTRAINT CK_SU_AUTH_SOURCE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2443, -942) THEN RAISE; END IF;
END;
/
ALTER TABLE SYSTEM_USERS ADD CONSTRAINT CK_SU_AUTH_SOURCE CHECK (AUTH_SOURCE IN ('LOCAL','LDAP'));
