-- Resolve native organization access through the active Human PRIMARY_OWNER.
-- An explicit knowledge policy overrides legacy PUBLIC and owner visibility.
CREATE OR REPLACE DATA GRANT entities_agent_own
  AS SELECT ON ENTITIES
  WHERE (
    (ENTITY_TYPE<>'KNOWLEDGE' AND (VISIBILITY='PUBLIC'
      OR UPPER(REPLACE(OWNED_BY_AGENT,'-','_'))=ORA_END_USER_CONTEXT.username))
    OR (ENTITY_TYPE='KNOWLEDGE' AND (
      ENTITY_ID IN (
        SELECT k.ENTITY_ID FROM CX_KNOWLEDGE_ACCESS_POLICIES k
        WHERE k.STATUS='ACTIVE' AND k.VALID_FROM<=CURRENT_TIMESTAMP
          AND (k.VALID_UNTIL IS NULL OR k.VALID_UNTIL>CURRENT_TIMESTAMP)
          AND (k.SCOPE_TYPE='PUBLIC_COMPANY'
            OR (k.SCOPE_TYPE='PRINCIPAL_PRIVATE'
              AND UPPER(REPLACE(k.PRINCIPAL_ID,'-','_'))=ORA_END_USER_CONTEXT.username)
            OR (k.SCOPE_TYPE IN ('ORGANIZATION_SUBTREE','ORGANIZATION_LEVEL') AND EXISTS (
              SELECT 1 FROM CX_ORGANIZATION_MEMBERS m
              JOIN CX_ORGANIZATION_CLOSURE c ON c.DESCENDANT_ID=m.ORGANIZATION_ID
              JOIN CX_AGENT_RELATIONSHIPS r ON r.PRINCIPAL_ID=m.PRINCIPAL_ID
              JOIN CX_PRINCIPALS h ON h.PRINCIPAL_ID=r.PRINCIPAL_ID
              JOIN CX_PRINCIPALS a ON a.PRINCIPAL_ID=r.AGENT_ID
              JOIN CX_ORGANIZATIONS mo ON mo.ORGANIZATION_ID=m.ORGANIZATION_ID
              JOIN CX_ORGANIZATIONS ko ON ko.ORGANIZATION_ID=k.ORGANIZATION_ID
              WHERE UPPER(REPLACE(r.AGENT_ID,'-','_'))=ORA_END_USER_CONTEXT.username AND m.STATUS='ACTIVE'
                AND r.RELATIONSHIP_ROLE='PRIMARY_OWNER' AND r.STATUS='ACTIVE'
                AND (r.ENDED_AT IS NULL OR r.ENDED_AT>CURRENT_TIMESTAMP)
                AND h.PRINCIPAL_TYPE='HUMAN' AND h.STATUS='ACTIVE' AND a.STATUS='ACTIVE'
                AND mo.STATUS='ACTIVE' AND ko.STATUS='ACTIVE'
                AND mo.VALID_FROM<=CURRENT_TIMESTAMP AND (mo.VALID_UNTIL IS NULL OR mo.VALID_UNTIL>CURRENT_TIMESTAMP)
                AND ko.VALID_FROM<=CURRENT_TIMESTAMP AND (ko.VALID_UNTIL IS NULL OR ko.VALID_UNTIL>CURRENT_TIMESTAMP) AND m.VALID_FROM<=CURRENT_TIMESTAMP
                AND (m.VALID_UNTIL IS NULL OR m.VALID_UNTIL>CURRENT_TIMESTAMP)
                AND c.ANCESTOR_ID=k.ORGANIZATION_ID
                AND (k.SCOPE_TYPE='ORGANIZATION_SUBTREE' OR c.DEPTH<=k.HIERARCHY_DEPTH)))))
      OR (ENTITY_ID NOT IN (SELECT k.ENTITY_ID FROM CX_KNOWLEDGE_ACCESS_POLICIES k)
        AND (VISIBILITY='PUBLIC' OR UPPER(REPLACE(OWNED_BY_AGENT,'-','_'))=ORA_END_USER_CONTEXT.username))
    ))
  )
  TO agent_data_role;
