-- Expose only the authenticated Agent's owner and ancestor chain to the native
-- knowledge predicate. No human identity/credential table or mutation grant.
CREATE OR REPLACE DATA GRANT org_agent_relationship_read
  AS SELECT ON CX_AGENT_RELATIONSHIPS
  WHERE UPPER(REPLACE(AGENT_ID,'-','_'))=ORA_END_USER_CONTEXT.username
    AND RELATIONSHIP_ROLE='PRIMARY_OWNER' AND STATUS='ACTIVE'
    AND (ENDED_AT IS NULL OR ENDED_AT>CURRENT_TIMESTAMP)
  TO agent_data_role;

CREATE OR REPLACE DATA GRANT gw_agent_principals
  AS SELECT ON CX_PRINCIPALS
  WHERE UPPER(REPLACE(PRINCIPAL_ID,'-','_'))=ORA_END_USER_CONTEXT.username
  TO agent_data_role;

CREATE OR REPLACE DATA GRANT org_agent_owner_principal_read
  AS SELECT ON CX_PRINCIPALS
  WHERE PRINCIPAL_TYPE='HUMAN' AND PRINCIPAL_ID IN (
    SELECT r.PRINCIPAL_ID FROM CX_AGENT_RELATIONSHIPS r
    WHERE UPPER(REPLACE(r.AGENT_ID,'-','_'))=ORA_END_USER_CONTEXT.username
      AND r.RELATIONSHIP_ROLE='PRIMARY_OWNER' AND r.STATUS='ACTIVE'
      AND (r.ENDED_AT IS NULL OR r.ENDED_AT>CURRENT_TIMESTAMP))
  TO agent_data_role;

CREATE OR REPLACE DATA GRANT org_agent_member_read
  AS SELECT ON CX_ORGANIZATION_MEMBERS
  WHERE STATUS='ACTIVE' AND VALID_FROM<=CURRENT_TIMESTAMP
    AND (VALID_UNTIL IS NULL OR VALID_UNTIL>CURRENT_TIMESTAMP)
    AND PRINCIPAL_ID IN (SELECT r.PRINCIPAL_ID FROM CX_AGENT_RELATIONSHIPS r
      WHERE UPPER(REPLACE(r.AGENT_ID,'-','_'))=ORA_END_USER_CONTEXT.username
        AND r.RELATIONSHIP_ROLE='PRIMARY_OWNER' AND r.STATUS='ACTIVE'
        AND (r.ENDED_AT IS NULL OR r.ENDED_AT>CURRENT_TIMESTAMP))
  TO agent_data_role;

CREATE OR REPLACE DATA GRANT org_agent_closure_read
  AS SELECT ON CX_ORGANIZATION_CLOSURE
  WHERE DESCENDANT_ID IN (SELECT m.ORGANIZATION_ID FROM CX_ORGANIZATION_MEMBERS m
    WHERE m.PRINCIPAL_ID IN (SELECT r.PRINCIPAL_ID FROM CX_AGENT_RELATIONSHIPS r
      WHERE UPPER(REPLACE(r.AGENT_ID,'-','_'))=ORA_END_USER_CONTEXT.username
        AND r.RELATIONSHIP_ROLE='PRIMARY_OWNER' AND r.STATUS='ACTIVE'))
  TO agent_data_role;

CREATE OR REPLACE DATA GRANT org_agent_ancestor_read
  AS SELECT ON CX_ORGANIZATIONS
  WHERE ORGANIZATION_ID IN (SELECT c.ANCESTOR_ID FROM CX_ORGANIZATION_CLOSURE c
    WHERE c.DESCENDANT_ID IN (SELECT m.ORGANIZATION_ID FROM CX_ORGANIZATION_MEMBERS m
      WHERE m.PRINCIPAL_ID IN (SELECT r.PRINCIPAL_ID FROM CX_AGENT_RELATIONSHIPS r
        WHERE UPPER(REPLACE(r.AGENT_ID,'-','_'))=ORA_END_USER_CONTEXT.username
          AND r.RELATIONSHIP_ROLE='PRIMARY_OWNER' AND r.STATUS='ACTIVE')))
  TO agent_data_role;
