-- AI Agent Infra v4.0.1 Oracle AI Database migration
CREATE TABLE EXECUTION_JOBS (
    JOB_ID VARCHAR2(64) PRIMARY KEY, JOB_TYPE VARCHAR2(32) NOT NULL,
    STATUS VARCHAR2(24) NOT NULL, AGENT_ID VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL, RESULT_JSON JSON, ERROR_MESSAGE VARCHAR2(2000),
    IDEMPOTENCY_KEY VARCHAR2(128) NOT NULL UNIQUE,
    ATTEMPT_COUNT NUMBER(5) DEFAULT 0 NOT NULL, MAX_ATTEMPTS NUMBER(5) DEFAULT 3 NOT NULL,
    LEASE_TOKEN VARCHAR2(128), LEASE_OWNER VARCHAR2(128), LEASE_UNTIL TIMESTAMP,
    REQUIRES_APPROVAL CHAR(1) DEFAULT 'Y' NOT NULL, APPROVED_BY VARCHAR2(64), APPROVED_AT TIMESTAMP,
    CANCEL_REQUESTED CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP,
    CONSTRAINT CK_EJ_STATUS CHECK (STATUS IN ('WAITING_APPROVAL','PENDING','RUNNING','RETRY','SUCCEEDED','FAILED','CANCELLED','REJECTED'))
);
CREATE INDEX IDX_EJ_CLAIM ON EXECUTION_JOBS(STATUS, CREATED_AT);
CREATE INDEX IDX_EJ_LEASE ON EXECUTION_JOBS(STATUS, LEASE_UNTIL);

CREATE TABLE EXECUTION_ATTEMPTS (
    ATTEMPT_ID VARCHAR2(64) PRIMARY KEY, JOB_ID VARCHAR2(64) NOT NULL,
    ATTEMPT_NUMBER NUMBER(5) NOT NULL, LEASE_TOKEN VARCHAR2(128) NOT NULL,
    WORKER_ID VARCHAR2(128) NOT NULL, STATUS VARCHAR2(24) NOT NULL,
    RESULT_JSON JSON, ERROR_MESSAGE VARCHAR2(2000),
    STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP,
    CONSTRAINT FK_EA_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOBS(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT UK_EA_ATTEMPT UNIQUE (JOB_ID, ATTEMPT_NUMBER)
);

CREATE TABLE EXECUTION_POLICIES (
    POLICY_ID VARCHAR2(64) PRIMARY KEY, POLICY_NAME VARCHAR2(128) NOT NULL UNIQUE,
    JOB_TYPE VARCHAR2(32), POLICY_JSON JSON NOT NULL, ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE EXECUTION_ARTIFACTS (
    ARTIFACT_ID VARCHAR2(64) PRIMARY KEY, JOB_ID VARCHAR2(64) NOT NULL,
    ARTIFACT_TYPE VARCHAR2(32) NOT NULL, ARTIFACT_URI VARCHAR2(1000) NOT NULL,
    CONTENT_HASH VARCHAR2(64) NOT NULL, SIZE_BYTES NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_EAR_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOBS(JOB_ID) ON DELETE CASCADE
);

CREATE TABLE EXECUTION_AUDIT (
    AUDIT_ID VARCHAR2(64) PRIMARY KEY, JOB_ID VARCHAR2(64) NOT NULL,
    ACTION_TYPE VARCHAR2(32) NOT NULL, ACTOR_ID VARCHAR2(128) NOT NULL,
    DETAIL_JSON JSON, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_EAU_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOBS(JOB_ID) ON DELETE CASCADE
);
COMMIT;

DECLARE
    v_table_count NUMBER;
    v_column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_count
    FROM USER_TABLES
    WHERE TABLE_NAME = 'APPROVAL_REQUESTS';

    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE APPROVAL_REQUESTS (
                APPROVAL_ID VARCHAR2(64) PRIMARY KEY,
                ENTITY_TYPE VARCHAR2(32) NOT NULL,
                ENTITY_ID VARCHAR2(64) NOT NULL,
                REQUESTED_BY VARCHAR2(64) NOT NULL,
                APPROVAL_STATUS VARCHAR2(16) DEFAULT 'PENDING' NOT NULL,
                APPROVED_BY VARCHAR2(64),
                APPROVED_AT TIMESTAMP,
                REJECT_REASON VARCHAR2(500),
                CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT CK_APPROVAL_STATUS CHECK (APPROVAL_STATUS IN ('PENDING','APPROVED','REJECTED')),
                CONSTRAINT CK_APPROVAL_ENTITY CHECK (ENTITY_TYPE IN ('STEP','LOOP','TOOL'))
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_column_count
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_APPROVAL_STATUS';
    IF v_column_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_APPROVAL_STATUS ON ' ||
            'APPROVAL_REQUESTS(APPROVAL_STATUS, CREATED_AT DESC)';
    END IF;

    SELECT COUNT(*) INTO v_column_count
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_APPROVAL_ENTITY';
    IF v_column_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_APPROVAL_ENTITY ON ' ||
            'APPROVAL_REQUESTS(ENTITY_TYPE, ENTITY_ID)';
    END IF;

    SELECT COUNT(*) INTO v_column_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'APPROVAL_REQUESTS'
      AND COLUMN_NAME = 'SLA_DEADLINE';

    IF v_column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE APPROVAL_REQUESTS ADD (' ||
            'SLA_DEADLINE TIMESTAMP, SLA_ESCALATE_TO VARCHAR2(64))';
    END IF;
END;
/
ALTER TABLE HARNESS_META ADD (PARENT_TEMPLATE_ID VARCHAR2(64));
ALTER TABLE ENTITY_EMBEDDINGS ADD (EMBEDDING_VERSION NUMBER DEFAULT 1 NOT NULL);

CREATE TABLE EVENT_DEAD_LETTER (
    DEAD_LETTER_ID VARCHAR2(64) PRIMARY KEY, ORIGINAL_EVENT_ID VARCHAR2(64),
    AGENT_ID VARCHAR2(64), EVENT_TYPE VARCHAR2(128), EVENT_PAYLOAD CLOB,
    FAILURE_REASON VARCHAR2(4000), RETRY_COUNT NUMBER DEFAULT 0,
    MAX_RETRIES NUMBER DEFAULT 5, STATUS VARCHAR2(32) DEFAULT 'PENDING',
    FIRST_FAILED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, LAST_RETRY_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_EDL_STATUS ON EVENT_DEAD_LETTER(STATUS);
CREATE INDEX IDX_EDL_AGENT ON EVENT_DEAD_LETTER(AGENT_ID);

CREATE TABLE DAG_EXECUTION_LOG (
    LOG_ID VARCHAR2(64) PRIMARY KEY, PLAN_ID VARCHAR2(64), STEP_ID VARCHAR2(64),
    AGENT_ID VARCHAR2(64), EXECUTION_STATUS VARCHAR2(32), STARTED_AT TIMESTAMP,
    COMPLETED_AT TIMESTAMP, DURATION_MS NUMBER, ERROR_MESSAGE CLOB,
    RETRY_COUNT NUMBER DEFAULT 0, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_DEL_PLAN ON DAG_EXECUTION_LOG(PLAN_ID);
CREATE INDEX IDX_DEL_STEP ON DAG_EXECUTION_LOG(STEP_ID);

CREATE TABLE ALERT_RULES (
    RULE_ID VARCHAR2(64) PRIMARY KEY, RULE_NAME VARCHAR2(255) NOT NULL,
    AGENT_ID VARCHAR2(128), METRIC_NAME VARCHAR2(128) NOT NULL,
    OPERATOR VARCHAR2(8) NOT NULL, THRESHOLD NUMBER NOT NULL,
    ACTION VARCHAR2(64) NOT NULL, ACTION_CONFIG CLOB,
    ENABLED CHAR(1) DEFAULT 'Y', COOLDOWN_MINUTES NUMBER DEFAULT 30,
    LAST_TRIGGERED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
