-- Idempotent public product knowledge used by the v4.4.13 Portal.
MERGE INTO ENTITIES e USING (
 SELECT 'CXK_V4413_OVERVIEW' id,'川序 v4.4.13 平台总览' title,'川序是以数据库为权威控制面的企业 AI Agent 管理平台。' summary,'川序（Chuanxu），技术工程名称 AI Agent Infra with DB，是用于部署、运营、治理和协作 AI Agent 的平台，不是单一聊天机器人。v4.4.13 为 Development Candidate，已完成工程验证但仍需独立人工审核，不能表述为正式公开发布或生产批准。平台统一管理 Human 与 Agent 的身份、权限、注册、凭据、生命周期和归属，提供 Agent Pool、Portal、知识、记忆、任务、工作区、Skills、工具、分支、循环、频道、审批、审计、合规、安全域、模型、部署、监控与大屏。核心原则是数据库权威、最小权限、双主体授权、显式治理、全链路审计和跨数据库一致语义。' content FROM DUAL UNION ALL
 SELECT 'CXK_V4413_PORTAL','川序 v4.4.13 Portal 与知识增强问答','Portal 使用授权知识与获准模型提供知识增强问答。','Portal 是用户连接获准 Agent Pool 智能体的问答入口。登录受身份、入口权限、MFA、连接配额、页面租约、Agent 注册与数据库连接能力约束。问答先验证用户与 Agent 都有 knowledge.read，再检索双方共同可访问的有效知识。命中时由获准 LLM 基于材料生成自然语言回答并附引用；未命中时，若 KNOWLEDGE_FIRST 策略允许模型补充，则使用模型通用能力并明确其不是企业政策。引用前重新校验权限、状态、有效期和摘要，输入、知识及完整输出都经过内容安全检查。' FROM DUAL UNION ALL
 SELECT 'CXK_V4413_SECURITY','川序 v4.4.13 身份权限与安全治理','Human 与 Agent 均是受治理主体，敏感操作受权限与审计约束。','川序将 Human 和 Agent 都建模为受治理主体。用户通过角色、权限覆盖、委派、组织关系和安全域获得有限访问；Agent 必须注册、激活并验证凭据。平台支持登录锁定、MFA、凭据生命周期、会话策略、Portal 连接限制、Agent containment、审批、审计与合规。高影响阻断要求不可变 Action Card 和另一名授权人员确认。v4.4.13 检查用户输入、知识内容与完整有界模型输出，包括跨流式分片的凭据特征；授权或能力服务不可用时失败关闭。' FROM DUAL UNION ALL
 SELECT 'CXK_V4413_COLLAB','川序 v4.4.13 Agent 协作与工作管理','平台统一管理 Agent Pool、任务、工作区、协作与扩展能力。','川序支持 Agent 注册、Agent Pool 分配、心跳、休眠、释放、转移、下线和隔离。Agent 能力说明不等同于授权，操作仍由数据库权限裁决。任务、工作区、上下文链、分支、循环与协作组组织长期工作；WORKSPACE_CONTEXT 保存聊天、检查点、交接、摘要、错误和分支点。频道支持显式成员、提及、动作卡和安全域边界。Skills 与工具支持列表、查看、编辑、下载、停用或软删除，写操作受专门权限和 CSRF 保护。' FROM DUAL UNION ALL
 SELECT 'CXK_V4413_DATA','川序 v4.4.13 数据模型、审计与运维','统一实体、能力注册表和审计构成平台数据与运维基础。','川序以统一实体保存知识、记忆、任务输出、经验、规格、技能、循环定义、Agent 与审批，并以实体边表达关系。知识和记忆保存元数据、可见性、所有者、有效期与访问策略。平台能力开关位于 CX_PLATFORM_CAPABILITIES 并校验依赖。运维包括预检、迁移、配置向导、健康检查、模型与 Embedding 治理、审计导出和保留策略。v4.4.13 增加 Agent 诊断、发现与审批摘要、能力发现及跨进程租约和 fencing 恢复证据。' FROM DUAL UNION ALL
 SELECT 'CXK_V4413_DB','川序 v4.4.13 Oracle Enterprise 数据库能力','Oracle Enterprise 适配器的版本基线与数据库原生能力。','当前适配器为川序 v4.4.13 Oracle Enterprise Edition，数据库基线为 Oracle AI Database 26ai 23.26.2+。它支持 Schema Owner 与 Business Agent 双访问路径、数据库本地 End User、角色隔离、Oracle Text、复合分区与引用分区、Property Graph 投影、JSON Duality View、Scheduler 作业和 Deep Security/MAC 策略。适配器承载身份、Agent 注册、权限、Portal 租约、知识、记忆、工作区、任务、Skills、工具、频道、审批、审计与合规。候选版本已验证干净初始化、外部 Agent、原生授权与并发、Portal 策略、模板继承及发布版本不可变性，但仍不等同于正式发布批准。' FROM DUAL
) s ON (e.ENTITY_TYPE='KNOWLEDGE' AND e.TITLE=s.title)
WHEN MATCHED THEN UPDATE SET e.CONTENT=s.content,e.SUMMARY=s.summary,e.CATEGORY='PRODUCT',e.STATUS='ACTIVE',e.VISIBILITY='PUBLIC',e.IMPORTANCE=10,e.UPDATED_AT=CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN INSERT (ENTITY_ID,ENTITY_TYPE,TITLE,CONTENT,SUMMARY,CATEGORY,STATUS,VISIBILITY,IMPORTANCE) VALUES (s.id,'KNOWLEDGE',s.title,s.content,s.summary,'PRODUCT','ACTIVE','PUBLIC',10);

UPDATE ENTITIES SET CONTENT=CONTENT||' Chuanxu, whose engineering name is AI Agent Infra with DB, is a database-authoritative enterprise platform for deploying, operating, governing, and coordinating AI Agents. Version 4.4.13 is a Development Candidate pending independent human review; it is not a public-release or production-approval claim.' WHERE ENTITY_ID='CXK_V4413_OVERVIEW';
UPDATE ENTITIES SET CONTENT=CONTENT||' Portal checks knowledge.read for both the Human and assigned Agent, retrieves only their shared authorized Knowledge, and lets an approved LLM produce cited answers. When no Knowledge matches, policy may allow a clearly labeled general-model answer. Without a model, authorized extracts remain available.' WHERE ENTITY_ID='CXK_V4413_PORTAL';
UPDATE ENTITIES SET CONTENT=CONTENT||' Humans and Agents are governed principals. Roles, overrides, delegations, organizations, and Security Domains determine access. Registration, credential proof, MFA, session policy, approvals, audit, compliance, and fail-closed content checks protect the platform.' WHERE ENTITY_ID='CXK_V4413_SECURITY';
UPDATE ENTITIES SET CONTENT=CONTENT||' Chuanxu governs Agent Pool assignment and release, durable Tasks and Workspaces, context lineage, Branches, Loops, Channels, Action Cards, Skills, Tools, and Security Domain boundaries.' WHERE ENTITY_ID='CXK_V4413_COLLAB';
UPDATE ENTITIES SET CONTENT=CONTENT||' Unified entities store Knowledge, Memory, outputs, experience, Specs, Skills, Agents, and approvals, while edges preserve relationships. Operations cover preflight, migration, health, model and Embedding governance, retention, diagnostics, and lease-fencing recovery evidence.' WHERE ENTITY_ID='CXK_V4413_DATA';
UPDATE ENTITIES SET CONTENT=CONTENT||' The Oracle AI Database 26ai 23.26.2+ adapter provides independent Agent database identities, Oracle Text, partitioning, Property Graph projections, JSON Duality Views, Scheduler jobs, and database-native security controls under the same Chuanxu governance API.' WHERE ENTITY_ID='CXK_V4413_DB';

MERGE INTO KNOWLEDGE_META km USING (SELECT ENTITY_ID FROM ENTITIES WHERE ENTITY_TYPE='KNOWLEDGE' AND TITLE LIKE '川序 v4.4.13%') e
ON (km.ENTITY_ID=e.ENTITY_ID AND km.ENTITY_TYPE='KNOWLEDGE')
WHEN NOT MATCHED THEN INSERT (ENTITY_ID,ENTITY_TYPE,DOMAIN,TOPIC,DIFFICULTY) VALUES (e.ENTITY_ID,'KNOWLEDGE','PLATFORM','Chuanxu v4.4.13','INTERMEDIATE');
