-- v4.4.15 task-subsystem online migration control. This is metadata only;
-- it does not switch TASK_STEPS or freeze platform-wide traffic.
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CX_TASK_MIGRATION_CONTROL (
    MIGRATION_KEY VARCHAR2(64) PRIMARY KEY,
    STATE VARCHAR2(20) NOT NULL,
    VERSION NUMBER(20,0) DEFAULT 1 NOT NULL,
    UPDATED_BY VARCHAR2(128) NOT NULL,
    REASON VARCHAR2(2000) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_CX_TASK_MIGRATION_STATE CHECK (STATE IN (''PREPARING'',''DUAL_WRITE'',''CUTOVER'',''VERIFIED'',''ROLLBACK''))
  )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
MERGE INTO CX_TASK_MIGRATION_CONTROL t USING (SELECT 'TASK_STEPS' k FROM dual) s
ON (t.MIGRATION_KEY=s.k)
WHEN NOT MATCHED THEN INSERT (MIGRATION_KEY,STATE,UPDATED_BY,REASON) VALUES ('TASK_STEPS','PREPARING','SYSTEM_BOOTSTRAP','v4.4.15 online task migration');
