-- ============================================================================
-- Oracle Memory System v1.0.0 - Knowledge Base Schema (Simplified)
-- ============================================================================
-- Description: Database schema for Knowledge Base
-- Version: 1.0.0-KB
-- Author: Haiwen Yin (胖头鱼 🐟)
-- Date: 2026-05-09
-- ============================================================================

-- ============================================================================
-- SECTION 1: KNOWLEDGE CONCEPTS - Core knowledge entities
-- ============================================================================

CREATE TABLE KNOWLEDGE_CONCEPTS (
    CONCEPT_ID      NUMBER PRIMARY KEY,
    CONCEPT_NAME    VARCHAR2(200) NOT NULL,
    CONCEPT_TYPE    VARCHAR2(50) NOT NULL,
    CATEGORY        VARCHAR2(100),
    TITLE           VARCHAR2(500),
    DESCRIPTION     CLOB,
    CONTENT         CLOB,
    SOURCE_TYPE     VARCHAR2(50) DEFAULT 'MANUAL',
    SOURCE_MEMORY_IDS CLOB,
    CONFIDENCE      NUMBER(3,2) DEFAULT 0.8,
    VALIDATION_STATUS VARCHAR2(30) DEFAULT 'PENDING',
    EMBEDDING       VECTOR(1024),
    TAGS            CLOB,
    METADATA        CLOB,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    VALIDATED_AT    TIMESTAMP WITH TIME ZONE,
    DEPRECATED_AT   TIMESTAMP WITH TIME ZONE,
    VERSION         NUMBER DEFAULT 1,
    IS_CURRENT      VARCHAR2(1) DEFAULT 'Y'
);

CREATE INDEX IDX_KC_TYPE ON KNOWLEDGE_CONCEPTS(CONCEPT_TYPE);
CREATE INDEX IDX_KC_CATEGORY ON KNOWLEDGE_CONCEPTS(CATEGORY);
CREATE INDEX IDX_KC_VALIDATION ON KNOWLEDGE_CONCEPTS(VALIDATION_STATUS);

-- ============================================================================
-- SECTION 2: KNOWLEDGE GRAPH - Knowledge relationships
-- ============================================================================

CREATE TABLE KNOWLEDGE_GRAPH (
    RELATIONSHIP_ID   NUMBER PRIMARY KEY,
    SOURCE_CONCEPT_ID NUMBER NOT NULL REFERENCES KNOWLEDGE_CONCEPTS(CONCEPT_ID),
    TARGET_CONCEPT_ID NUMBER NOT NULL REFERENCES KNOWLEDGE_CONCEPTS(CONCEPT_ID),
    RELATIONSHIP_TYPE VARCHAR2(100) NOT NULL,
    RELATIONSHIP_STRENGTH NUMBER(3,2) DEFAULT 1.0,
    PROPERTIES        CLOB,
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    SOURCE_TYPE       VARCHAR2(50) DEFAULT 'MANUAL',
    CONFIDENCE        NUMBER(3,2) DEFAULT 0.8
);

CREATE INDEX IDX_KG_SOURCE ON KNOWLEDGE_GRAPH(SOURCE_CONCEPT_ID);
CREATE INDEX IDX_KG_TARGET ON KNOWLEDGE_GRAPH(TARGET_CONCEPT_ID);
CREATE INDEX IDX_KG_TYPE ON KNOWLEDGE_GRAPH(RELATIONSHIP_TYPE);

-- ============================================================================
-- SECTION 3: KNOWLEDGE_VERSIONS - Version history
-- ============================================================================

CREATE TABLE KNOWLEDGE_VERSIONS (
    VERSION_ID        NUMBER PRIMARY KEY,
    CONCEPT_ID        NUMBER NOT NULL REFERENCES KNOWLEDGE_CONCEPTS(CONCEPT_ID),
    TITLE             VARCHAR2(500),
    DESCRIPTION       CLOB,
    CONTENT           CLOB,
    CHANGE_SUMMARY    CLOB,
    CHANGE_REASON     VARCHAR2(500),
    VERSIONED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    VERSIONED_BY      VARCHAR2(64)
);

CREATE INDEX IDX_KV_CONCEPT ON KNOWLEDGE_VERSIONS(CONCEPT_ID);

-- ============================================================================
-- SECTION 4: KNOWLEDGE_TAGS - Tag-based categorization
-- ============================================================================

CREATE TABLE KNOWLEDGE_TAGS (
    TAG_ID            NUMBER PRIMARY KEY,
    TAG_NAME          VARCHAR2(100) NOT NULL UNIQUE,
    TAG_CATEGORY      VARCHAR2(50),
    USAGE_COUNT       NUMBER DEFAULT 0,
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP
);

CREATE TABLE KNOWLEDGE_CONCEPT_TAGS (
    CONCEPT_ID        NUMBER NOT NULL REFERENCES KNOWLEDGE_CONCEPTS(CONCEPT_ID),
    TAG_ID            NUMBER NOT NULL REFERENCES KNOWLEDGE_TAGS(TAG_ID),
    PRIMARY KEY (CONCEPT_ID, TAG_ID)
);

-- ============================================================================
-- SECTION 5: KNOWLEDGE_DISTILLATION_LOG - Distillation audit trail
-- ============================================================================

CREATE TABLE KNOWLEDGE_DISTILLATION_LOG (
    DISTILLATION_ID   NUMBER PRIMARY KEY,
    MEMORY_IDS        CLOB,
    MEMORY_COUNT      NUMBER,
    MEMORY_TIME_RANGE VARCHAR2(100),
    KNOWLEDGE_TYPE    VARCHAR2(50),
    KNOWLEDGE_TITLE   VARCHAR2(500),
    CONFIDENCE        NUMBER(3,2),
    DISTILLATION_METHOD VARCHAR2(50),
    TRIGGERED_BY      VARCHAR2(100),
    PATTERN_DETECTED  CLOB,
    KNOWLEDGE_ID      NUMBER REFERENCES KNOWLEDGE_CONCEPTS(CONCEPT_ID),
    STATUS            VARCHAR2(30) DEFAULT 'PENDING',
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    COMPLETED_AT      TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_KDL_CREATED ON KNOWLEDGE_DISTILLATION_LOG(CREATED_AT DESC);

-- ============================================================================
-- SECTION 6: KNOWLEDGE_SEARCH_HISTORY - Search analytics
-- ============================================================================

CREATE TABLE KNOWLEDGE_SEARCH_HISTORY (
    SEARCH_ID         NUMBER PRIMARY KEY,
    QUERY_TEXT        CLOB,
    QUERY_EMBEDDING   VECTOR(1024),
    RESULT_COUNT      NUMBER,
    TOP_RESULT_ID     NUMBER REFERENCES KNOWLEDGE_CONCEPTS(CONCEPT_ID),
    RELEVANCE_SCORE   NUMBER(3,2),
    USER_CLICKED      VARCHAR2(1) DEFAULT 'N',
    USER_HELPFUL      VARCHAR2(1),
    SEARCH_CONTEXT    VARCHAR2(50),
    SESSION_ID        NUMBER,
    SEARCHED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_KSH_SEARCHED ON KNOWLEDGE_SEARCH_HISTORY(SEARCHED_AT DESC);

-- ============================================================================
-- SECTION 7: Sequences
-- ============================================================================

CREATE SEQUENCE SEQ_KNOWLEDGE_CONCEPTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_KNOWLEDGE_GRAPH START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_KNOWLEDGE_VERSIONS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_KNOWLEDGE_TAGS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISTILLATION_LOG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SEARCH_HISTORY START WITH 1 INCREMENT BY 1;

-- ============================================================================
-- SECTION 8: Views
-- ============================================================================

CREATE OR REPLACE VIEW V_KNOWLEDGE_STATS_BY_TYPE AS
SELECT 
    CONCEPT_TYPE,
    COUNT(*) as TOTAL_COUNT,
    COUNT(CASE WHEN VALIDATION_STATUS = 'VALIDATED' THEN 1 END) as VALIDATED_COUNT,
    AVG(CONFIDENCE) as AVG_CONFIDENCE
FROM KNOWLEDGE_CONCEPTS
GROUP BY CONCEPT_TYPE;

CREATE OR REPLACE VIEW V_RECENTLY_VALIDATED AS
SELECT 
    CONCEPT_ID,
    CONCEPT_NAME,
    CONCEPT_TYPE,
    TITLE,
    CONFIDENCE,
    VALIDATED_AT
FROM KNOWLEDGE_CONCEPTS
WHERE VALIDATION_STATUS = 'VALIDATED'
ORDER BY VALIDATED_AT DESC
FETCH FIRST 20 ROWS ONLY;

-- ============================================================================
-- SECTION 9: Triggers
-- ============================================================================

CREATE OR REPLACE TRIGGER TRG_KC_UPDATED
BEFORE UPDATE ON KNOWLEDGE_CONCEPTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_KG_UPDATED
BEFORE UPDATE ON KNOWLEDGE_GRAPH
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ============================================================================
-- SECTION 10: Validation
-- ============================================================================

SELECT TABLE_NAME, NUM_ROWS FROM USER_TABLES WHERE TABLE_NAME LIKE 'KNOWLEDGE%' ORDER BY TABLE_NAME;
SELECT INDEX_NAME, TABLE_NAME FROM USER_INDEXES WHERE TABLE_NAME LIKE 'KNOWLEDGE%' ORDER BY TABLE_NAME;
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE 'SEQ_KNOWLEDGE%' OR SEQUENCE_NAME LIKE 'SEQ_DISTILLATION%' OR SEQUENCE_NAME LIKE 'SEQ_SEARCH%' ORDER BY SEQUENCE_NAME;
SELECT VIEW_NAME FROM USER_VIEWS WHERE VIEW_NAME LIKE 'V_KNOWLEDGE%' OR VIEW_NAME LIKE 'V_RECENTLY%' ORDER BY VIEW_NAME;

-- ============================================================================
-- SCHEMA DEPLOYMENT COMPLETE
-- ============================================================================
